package leads.capita.trade.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 10 11:25:05 ALMT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BdaPurchaseOrderVO_Not_UsedImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BdaPurchaseOrderVO_Not_UsedImpl() {
    }
}
