package leads.capita.trade.model.view;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 10 11:25:05 ALMT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BdaPurchaseOrderVO_Not_UsedRowImpl extends ViewRowImpl {
    public static final int ENTITY_BDAPURCHASEORDER = 0;
    public static final int ENTITY_INVESTORACCOUNTS = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AccountId {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getAccountId();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAccountId((Integer)value);
            }
        }
        ,
        PurchaseOrderId {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getPurchaseOrderId();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setPurchaseOrderId((DBSequence)value);
            }
        }
        ,
        InstrumentId {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getInstrumentId();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setInstrumentId((Integer)value);
            }
        }
        ,
        OrderQty {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setOrderQty((Integer)value);
            }
        }
        ,
        OrderDate {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getOrderDate();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setOrderDate((Timestamp)value);
            }
        }
        ,
        Status {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getStatus();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        InvestorCode {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getInvestorCode();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setInvestorCode((String)value);
            }
        }
        ,
        AccountId1 {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getAccountId1();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAccountId1((Long)value);
            }
        }
        ,
        Name {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getName();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Price {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getPrice();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setPrice((BigDecimal)value);
            }
        }
        ,
        AllocationDate {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getAllocationDate();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAllocationDate((Timestamp)value);
            }
        }
        ,
        AllocationQty {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getAllocationQty();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAllocationQty((Integer)value);
            }
        }
        ,
        InstrumentLOV {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getInstrumentLOV();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomLoookupLOV {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getCustomLoookupLOV();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InvestorAccountsLOV {
            public Object get(BdaPurchaseOrderVO_Not_UsedRowImpl obj) {
                return obj.getInvestorAccountsLOV();
            }

            public void put(BdaPurchaseOrderVO_Not_UsedRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BdaPurchaseOrderVO_Not_UsedRowImpl object);

        public abstract void put(BdaPurchaseOrderVO_Not_UsedRowImpl object, Object value);

        public int index() {
            return BdaPurchaseOrderVO_Not_UsedRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return BdaPurchaseOrderVO_Not_UsedRowImpl.AttributesEnum.firstIndex() + BdaPurchaseOrderVO_Not_UsedRowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = BdaPurchaseOrderVO_Not_UsedRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACCOUNTID = AttributesEnum.AccountId.index();
    public static final int PURCHASEORDERID = AttributesEnum.PurchaseOrderId.index();
    public static final int INSTRUMENTID = AttributesEnum.InstrumentId.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int ORDERDATE = AttributesEnum.OrderDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int INVESTORCODE = AttributesEnum.InvestorCode.index();
    public static final int ACCOUNTID1 = AttributesEnum.AccountId1.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int ALLOCATIONDATE = AttributesEnum.AllocationDate.index();
    public static final int ALLOCATIONQTY = AttributesEnum.AllocationQty.index();
    public static final int INSTRUMENTLOV = AttributesEnum.InstrumentLOV.index();
    public static final int CUSTOMLOOOKUPLOV = AttributesEnum.CustomLoookupLOV.index();
    public static final int INVESTORACCOUNTSLOV = AttributesEnum.InvestorAccountsLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BdaPurchaseOrderVO_Not_UsedRowImpl() {
    }

    /**
     * Gets BdaPurchaseOrder entity object.
     * @return the BdaPurchaseOrder
     */
    public EntityImpl getBdaPurchaseOrder() {
        return (EntityImpl)getEntity(ENTITY_BDAPURCHASEORDER);
    }

    /**
     * Gets InvestorAccounts entity object.
     * @return the InvestorAccounts
     */
    public EntityImpl getInvestorAccounts() {
        return (EntityImpl)getEntity(ENTITY_INVESTORACCOUNTS);
    }

    /**
     * Gets the attribute value for ACCOUNT_ID using the alias name AccountId.
     * @return the ACCOUNT_ID
     */
    public Integer getAccountId() {
        return (Integer) getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_ID using the alias name AccountId.
     * @param value value to set the ACCOUNT_ID
     */
    public void setAccountId(Integer value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for PURCHASE_ORDER_ID using the alias name PurchaseOrderId.
     * @return the PURCHASE_ORDER_ID
     */
    public DBSequence getPurchaseOrderId() {
        return (DBSequence)getAttributeInternal(PURCHASEORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for PURCHASE_ORDER_ID using the alias name PurchaseOrderId.
     * @param value value to set the PURCHASE_ORDER_ID
     */
    public void setPurchaseOrderId(DBSequence value) {
        setAttributeInternal(PURCHASEORDERID, value);
    }

    /**
     * Gets the attribute value for INSTRUMENT_ID using the alias name InstrumentId.
     * @return the INSTRUMENT_ID
     */
    public Integer getInstrumentId() {
        return (Integer) getAttributeInternal(INSTRUMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTRUMENT_ID using the alias name InstrumentId.
     * @param value value to set the INSTRUMENT_ID
     */
    public void setInstrumentId(Integer value) {
        setAttributeInternal(INSTRUMENTID, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Integer getOrderQty() {
        return (Integer) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Integer value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for ORDER_DATE using the alias name OrderDate.
     * @return the ORDER_DATE
     */
    public Timestamp getOrderDate() {
        return (Timestamp) getAttributeInternal(ORDERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_DATE using the alias name OrderDate.
     * @param value value to set the ORDER_DATE
     */
    public void setOrderDate(Timestamp value) {
        setAttributeInternal(ORDERDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for INVESTOR_CODE using the alias name InvestorCode.
     * @return the INVESTOR_CODE
     */
    public String getInvestorCode() {
        return (String) getAttributeInternal(INVESTORCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVESTOR_CODE using the alias name InvestorCode.
     * @param value value to set the INVESTOR_CODE
     */
    public void setInvestorCode(String value) {
        setAttributeInternal(INVESTORCODE, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_ID using the alias name AccountId1.
     * @return the ACCOUNT_ID
     */
    public Long getAccountId1() {
        return (Long) getAttributeInternal(ACCOUNTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_ID using the alias name AccountId1.
     * @param value value to set the ACCOUNT_ID
     */
    public void setAccountId1(Long value) {
        setAttributeInternal(ACCOUNTID1, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public BigDecimal getPrice() {
        return (BigDecimal) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(BigDecimal value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for ALLOCATION_DATE using the alias name AllocationDate.
     * @return the ALLOCATION_DATE
     */
    public Timestamp getAllocationDate() {
        return (Timestamp) getAttributeInternal(ALLOCATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_DATE using the alias name AllocationDate.
     * @param value value to set the ALLOCATION_DATE
     */
    public void setAllocationDate(Timestamp value) {
        setAttributeInternal(ALLOCATIONDATE, value);
    }

    /**
     * Gets the attribute value for ALLOCATION_QTY using the alias name AllocationQty.
     * @return the ALLOCATION_QTY
     */
    public Integer getAllocationQty() {
        return (Integer) getAttributeInternal(ALLOCATIONQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_QTY using the alias name AllocationQty.
     * @param value value to set the ALLOCATION_QTY
     */
    public void setAllocationQty(Integer value) {
        setAttributeInternal(ALLOCATIONQTY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InstrumentLOV.
     */
    public RowSet getInstrumentLOV() {
        return (RowSet)getAttributeInternal(INSTRUMENTLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomLoookupLOV.
     */
    public RowSet getCustomLoookupLOV() {
        return (RowSet)getAttributeInternal(CUSTOMLOOOKUPLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvestorAccountsLOV.
     */
    public RowSet getInvestorAccountsLOV() {
        return (RowSet)getAttributeInternal(INVESTORACCOUNTSLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
