package leads.capita.trade.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 29 17:00:29 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CSETradePriceFileVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TRADEPRICEFILE = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ClosePrice {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getClosePrice();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setClosePrice((BigDecimal)value);
            }
        }
        ,
        ExchangeId {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getExchangeId();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setExchangeId((Integer)value);
            }
        }
        ,
        HighPrice {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getHighPrice();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setHighPrice((BigDecimal)value);
            }
        }
        ,
        ImportId {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getImportId();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setImportId((Integer)value);
            }
        }
        ,
        InstrCode {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getInstrCode();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setInstrCode((String)value);
            }
        }
        ,
        InstrGroup {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getInstrGroup();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setInstrGroup((String)value);
            }
        }
        ,
        InstrIsin {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getInstrIsin();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setInstrIsin((String)value);
            }
        }
        ,
        LowPrice {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getLowPrice();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setLowPrice((BigDecimal)value);
            }
        }
        ,
        OpenPrice {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getOpenPrice();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setOpenPrice((BigDecimal)value);
            }
        }
        ,
        PriceDate {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getPriceDate();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setPriceDate((Timestamp)value);
            }
        }
        ,
        ProcDate {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getProcDate();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setProcDate((Timestamp)value);
            }
        }
        ,
        ProcStatus {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getProcStatus();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setProcStatus((String)value);
            }
        }
        ,
        RowID {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getRowID();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        TracerNo {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getTracerNo();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setTracerNo((Integer)value);
            }
        }
        ,
        ValidStatus {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getValidStatus();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setValidStatus((String)value);
            }
        }
        ,
        TradeTime {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getTradeTime();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setTradeTime((String)value);
            }
        }
        ,
        FileId {
            public Object get(CSETradePriceFileVORowImpl obj) {
                return obj.getFileId();
            }

            public void put(CSETradePriceFileVORowImpl obj, Object value) {
                obj.setFileId((Integer)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CSETradePriceFileVORowImpl object);

        public abstract void put(CSETradePriceFileVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLOSEPRICE = AttributesEnum.ClosePrice.index();
    public static final int EXCHANGEID = AttributesEnum.ExchangeId.index();
    public static final int HIGHPRICE = AttributesEnum.HighPrice.index();
    public static final int IMPORTID = AttributesEnum.ImportId.index();
    public static final int INSTRCODE = AttributesEnum.InstrCode.index();
    public static final int INSTRGROUP = AttributesEnum.InstrGroup.index();
    public static final int INSTRISIN = AttributesEnum.InstrIsin.index();
    public static final int LOWPRICE = AttributesEnum.LowPrice.index();
    public static final int OPENPRICE = AttributesEnum.OpenPrice.index();
    public static final int PRICEDATE = AttributesEnum.PriceDate.index();
    public static final int PROCDATE = AttributesEnum.ProcDate.index();
    public static final int PROCSTATUS = AttributesEnum.ProcStatus.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int TRACERNO = AttributesEnum.TracerNo.index();
    public static final int VALIDSTATUS = AttributesEnum.ValidStatus.index();
    public static final int TRADETIME = AttributesEnum.TradeTime.index();
    public static final int FILEID = AttributesEnum.FileId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CSETradePriceFileVORowImpl() {
    }

    /**
     * Gets TradePriceFile entity object.
     * @return the TradePriceFile
     */
    public EntityImpl getTradePriceFile() {
        return (EntityImpl)getEntity(ENTITY_TRADEPRICEFILE);
    }

    /**
     * Gets the attribute value for CLOSE_PRICE using the alias name ClosePrice.
     * @return the CLOSE_PRICE
     */
    public BigDecimal getClosePrice() {
        return (BigDecimal)getAttributeInternal(CLOSEPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_PRICE using the alias name ClosePrice.
     * @param value value to set the CLOSE_PRICE
     */
    public void setClosePrice(BigDecimal value) {
        setAttributeInternal(CLOSEPRICE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @return the EXCHANGE_ID
     */
    public Integer getExchangeId() {
        return (Integer)getAttributeInternal(EXCHANGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @param value value to set the EXCHANGE_ID
     */
    public void setExchangeId(Integer value) {
        setAttributeInternal(EXCHANGEID, value);
    }

    /**
     * Gets the attribute value for HIGH_PRICE using the alias name HighPrice.
     * @return the HIGH_PRICE
     */
    public BigDecimal getHighPrice() {
        return (BigDecimal)getAttributeInternal(HIGHPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for HIGH_PRICE using the alias name HighPrice.
     * @param value value to set the HIGH_PRICE
     */
    public void setHighPrice(BigDecimal value) {
        setAttributeInternal(HIGHPRICE, value);
    }

    /**
     * Gets the attribute value for IMPORT_ID using the alias name ImportId.
     * @return the IMPORT_ID
     */
    public Integer getImportId() {
        return (Integer)getAttributeInternal(IMPORTID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_ID using the alias name ImportId.
     * @param value value to set the IMPORT_ID
     */
    public void setImportId(Integer value) {
        setAttributeInternal(IMPORTID, value);
    }

    /**
     * Gets the attribute value for INSTR_CODE using the alias name InstrCode.
     * @return the INSTR_CODE
     */
    public String getInstrCode() {
        return (String)getAttributeInternal(INSTRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTR_CODE using the alias name InstrCode.
     * @param value value to set the INSTR_CODE
     */
    public void setInstrCode(String value) {
        setAttributeInternal(INSTRCODE, value);
    }

    /**
     * Gets the attribute value for INSTR_GROUP using the alias name InstrGroup.
     * @return the INSTR_GROUP
     */
    public String getInstrGroup() {
        return (String)getAttributeInternal(INSTRGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTR_GROUP using the alias name InstrGroup.
     * @param value value to set the INSTR_GROUP
     */
    public void setInstrGroup(String value) {
        setAttributeInternal(INSTRGROUP, value);
    }

    /**
     * Gets the attribute value for INSTR_ISIN using the alias name InstrIsin.
     * @return the INSTR_ISIN
     */
    public String getInstrIsin() {
        return (String)getAttributeInternal(INSTRISIN);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTR_ISIN using the alias name InstrIsin.
     * @param value value to set the INSTR_ISIN
     */
    public void setInstrIsin(String value) {
        setAttributeInternal(INSTRISIN, value);
    }

    /**
     * Gets the attribute value for LOW_PRICE using the alias name LowPrice.
     * @return the LOW_PRICE
     */
    public BigDecimal getLowPrice() {
        return (BigDecimal)getAttributeInternal(LOWPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOW_PRICE using the alias name LowPrice.
     * @param value value to set the LOW_PRICE
     */
    public void setLowPrice(BigDecimal value) {
        setAttributeInternal(LOWPRICE, value);
    }

    /**
     * Gets the attribute value for OPEN_PRICE using the alias name OpenPrice.
     * @return the OPEN_PRICE
     */
    public BigDecimal getOpenPrice() {
        return (BigDecimal)getAttributeInternal(OPENPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPEN_PRICE using the alias name OpenPrice.
     * @param value value to set the OPEN_PRICE
     */
    public void setOpenPrice(BigDecimal value) {
        setAttributeInternal(OPENPRICE, value);
    }

    /**
     * Gets the attribute value for PRICE_DATE using the alias name PriceDate.
     * @return the PRICE_DATE
     */
    public Timestamp getPriceDate() {
        return (Timestamp)getAttributeInternal(PRICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE_DATE using the alias name PriceDate.
     * @param value value to set the PRICE_DATE
     */
    public void setPriceDate(Timestamp value) {
        setAttributeInternal(PRICEDATE, value);
    }

    /**
     * Gets the attribute value for PROC_DATE using the alias name ProcDate.
     * @return the PROC_DATE
     */
    public Timestamp getProcDate() {
        return (Timestamp)getAttributeInternal(PROCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROC_DATE using the alias name ProcDate.
     * @param value value to set the PROC_DATE
     */
    public void setProcDate(Timestamp value) {
        setAttributeInternal(PROCDATE, value);
    }

    /**
     * Gets the attribute value for PROC_STATUS using the alias name ProcStatus.
     * @return the PROC_STATUS
     */
    public String getProcStatus() {
        return (String)getAttributeInternal(PROCSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PROC_STATUS using the alias name ProcStatus.
     * @param value value to set the PROC_STATUS
     */
    public void setProcStatus(String value) {
        setAttributeInternal(PROCSTATUS, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for TRACER_NO using the alias name TracerNo.
     * @return the TRACER_NO
     */
    public Integer getTracerNo() {
        return (Integer)getAttributeInternal(TRACERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TRACER_NO using the alias name TracerNo.
     * @param value value to set the TRACER_NO
     */
    public void setTracerNo(Integer value) {
        setAttributeInternal(TRACERNO, value);
    }

    /**
     * Gets the attribute value for VALID_STATUS using the alias name ValidStatus.
     * @return the VALID_STATUS
     */
    public String getValidStatus() {
        return (String)getAttributeInternal(VALIDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for VALID_STATUS using the alias name ValidStatus.
     * @param value value to set the VALID_STATUS
     */
    public void setValidStatus(String value) {
        setAttributeInternal(VALIDSTATUS, value);
    }

    /**
     * Gets the attribute value for TRADE_TIME using the alias name TradeTime.
     * @return the TRADE_TIME
     */
    public String getTradeTime() {
        return (String)getAttributeInternal(TRADETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_TIME using the alias name TradeTime.
     * @param value value to set the TRADE_TIME
     */
    public void setTradeTime(String value) {
        setAttributeInternal(TRADETIME, value);
    }

    /**
     * Gets the attribute value for FILE_ID using the alias name FileId.
     * @return the FILE_ID
     */
    public Integer getFileId() {
        return (Integer) getAttributeInternal(FILEID);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_ID using the alias name FileId.
     * @param value value to set the FILE_ID
     */
    public void setFileId(Integer value) {
        setAttributeInternal(FILEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
