package leads.capita.trade.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 15 11:48:34 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EodTickerVORowImpl extends ViewRowImpl {
    public static final int ENTITY_EODTICKER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        FileId {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getFileId();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setFileId((Long)value);
            }
        }
        ,
        ExchangeId {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getExchangeId();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setExchangeId((Integer)value);
            }
        }
        ,
        TradeDate {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getTradeDate();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setTradeDate((String)value);
            }
        }
        ,
        TradeTime {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getTradeTime();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setTradeTime((String)value);
            }
        }
        ,
        SecurityCode {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getSecurityCode();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setSecurityCode((String)value);
            }
        }
        ,
        Isin {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getIsin();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setIsin((String)value);
            }
        }
        ,
        InstrCategory {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getInstrCategory();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setInstrCategory((String)value);
            }
        }
        ,
        OpenPrice {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getOpenPrice();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setOpenPrice((BigDecimal)value);
            }
        }
        ,
        HighPrice {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getHighPrice();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setHighPrice((BigDecimal)value);
            }
        }
        ,
        LowPrice {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getLowPrice();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setLowPrice((BigDecimal)value);
            }
        }
        ,
        ClosePrice {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getClosePrice();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setClosePrice((BigDecimal)value);
            }
        }
        ,
        CompulsorySpot {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getCompulsorySpot();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setCompulsorySpot((String)value);
            }
        }
        ,
        Sector {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getSector();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setSector((String)value);
            }
        }
        ,
        TickVar {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getTickVar();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setTickVar((Integer)value);
            }
        }
        ,
        VarPercent {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getVarPercent();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setVarPercent((Integer)value);
            }
        }
        ,
        AssetClass {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getAssetClass();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setAssetClass((String)value);
            }
        }
        ,
        SeqNo {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getSeqNo();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setSeqNo((DBSequence)value);
            }
        }
        ,
        FileName {
            public Object get(EodTickerVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(EodTickerVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EodTickerVORowImpl object);

        public abstract void put(EodTickerVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FILEID = AttributesEnum.FileId.index();
    public static final int EXCHANGEID = AttributesEnum.ExchangeId.index();
    public static final int TRADEDATE = AttributesEnum.TradeDate.index();
    public static final int TRADETIME = AttributesEnum.TradeTime.index();
    public static final int SECURITYCODE = AttributesEnum.SecurityCode.index();
    public static final int ISIN = AttributesEnum.Isin.index();
    public static final int INSTRCATEGORY = AttributesEnum.InstrCategory.index();
    public static final int OPENPRICE = AttributesEnum.OpenPrice.index();
    public static final int HIGHPRICE = AttributesEnum.HighPrice.index();
    public static final int LOWPRICE = AttributesEnum.LowPrice.index();
    public static final int CLOSEPRICE = AttributesEnum.ClosePrice.index();
    public static final int COMPULSORYSPOT = AttributesEnum.CompulsorySpot.index();
    public static final int SECTOR = AttributesEnum.Sector.index();
    public static final int TICKVAR = AttributesEnum.TickVar.index();
    public static final int VARPERCENT = AttributesEnum.VarPercent.index();
    public static final int ASSETCLASS = AttributesEnum.AssetClass.index();
    public static final int SEQNO = AttributesEnum.SeqNo.index();
    public static final int FILENAME = AttributesEnum.FileName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EodTickerVORowImpl() {
    }

    /**
     * Gets EodTicker entity object.
     * @return the EodTicker
     */
    public EntityImpl getEodTicker() {
        return (EntityImpl)getEntity(ENTITY_EODTICKER);
    }

    /**
     * Gets the attribute value for FILE_ID using the alias name FileId.
     * @return the FILE_ID
     */
    public Long getFileId() {
        return (Long) getAttributeInternal(FILEID);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_ID using the alias name FileId.
     * @param value value to set the FILE_ID
     */
    public void setFileId(Long value) {
        setAttributeInternal(FILEID, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @return the EXCHANGE_ID
     */
    public Integer getExchangeId() {
        return (Integer) getAttributeInternal(EXCHANGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @param value value to set the EXCHANGE_ID
     */
    public void setExchangeId(Integer value) {
        setAttributeInternal(EXCHANGEID, value);
    }

    /**
     * Gets the attribute value for TRADE_DATE using the alias name TradeDate.
     * @return the TRADE_DATE
     */
    public String getTradeDate() {
        return (String) getAttributeInternal(TRADEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_DATE using the alias name TradeDate.
     * @param value value to set the TRADE_DATE
     */
    public void setTradeDate(String value) {
        setAttributeInternal(TRADEDATE, value);
    }

    /**
     * Gets the attribute value for TRADE_TIME using the alias name TradeTime.
     * @return the TRADE_TIME
     */
    public String getTradeTime() {
        return (String) getAttributeInternal(TRADETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_TIME using the alias name TradeTime.
     * @param value value to set the TRADE_TIME
     */
    public void setTradeTime(String value) {
        setAttributeInternal(TRADETIME, value);
    }

    /**
     * Gets the attribute value for SECURITY_CODE using the alias name SecurityCode.
     * @return the SECURITY_CODE
     */
    public String getSecurityCode() {
        return (String) getAttributeInternal(SECURITYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SECURITY_CODE using the alias name SecurityCode.
     * @param value value to set the SECURITY_CODE
     */
    public void setSecurityCode(String value) {
        setAttributeInternal(SECURITYCODE, value);
    }

    /**
     * Gets the attribute value for ISIN using the alias name Isin.
     * @return the ISIN
     */
    public String getIsin() {
        return (String) getAttributeInternal(ISIN);
    }

    /**
     * Sets <code>value</code> as attribute value for ISIN using the alias name Isin.
     * @param value value to set the ISIN
     */
    public void setIsin(String value) {
        setAttributeInternal(ISIN, value);
    }

    /**
     * Gets the attribute value for INSTR_CATEGORY using the alias name InstrCategory.
     * @return the INSTR_CATEGORY
     */
    public String getInstrCategory() {
        return (String) getAttributeInternal(INSTRCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTR_CATEGORY using the alias name InstrCategory.
     * @param value value to set the INSTR_CATEGORY
     */
    public void setInstrCategory(String value) {
        setAttributeInternal(INSTRCATEGORY, value);
    }

    /**
     * Gets the attribute value for OPEN_PRICE using the alias name OpenPrice.
     * @return the OPEN_PRICE
     */
    public BigDecimal getOpenPrice() {
        return (BigDecimal) getAttributeInternal(OPENPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPEN_PRICE using the alias name OpenPrice.
     * @param value value to set the OPEN_PRICE
     */
    public void setOpenPrice(BigDecimal value) {
        setAttributeInternal(OPENPRICE, value);
    }

    /**
     * Gets the attribute value for HIGH_PRICE using the alias name HighPrice.
     * @return the HIGH_PRICE
     */
    public BigDecimal getHighPrice() {
        return (BigDecimal) getAttributeInternal(HIGHPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for HIGH_PRICE using the alias name HighPrice.
     * @param value value to set the HIGH_PRICE
     */
    public void setHighPrice(BigDecimal value) {
        setAttributeInternal(HIGHPRICE, value);
    }

    /**
     * Gets the attribute value for LOW_PRICE using the alias name LowPrice.
     * @return the LOW_PRICE
     */
    public BigDecimal getLowPrice() {
        return (BigDecimal) getAttributeInternal(LOWPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOW_PRICE using the alias name LowPrice.
     * @param value value to set the LOW_PRICE
     */
    public void setLowPrice(BigDecimal value) {
        setAttributeInternal(LOWPRICE, value);
    }

    /**
     * Gets the attribute value for CLOSE_PRICE using the alias name ClosePrice.
     * @return the CLOSE_PRICE
     */
    public BigDecimal getClosePrice() {
        return (BigDecimal) getAttributeInternal(CLOSEPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_PRICE using the alias name ClosePrice.
     * @param value value to set the CLOSE_PRICE
     */
    public void setClosePrice(BigDecimal value) {
        setAttributeInternal(CLOSEPRICE, value);
    }

    /**
     * Gets the attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @return the COMPULSORY_SPOT
     */
    public String getCompulsorySpot() {
        return (String) getAttributeInternal(COMPULSORYSPOT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @param value value to set the COMPULSORY_SPOT
     */
    public void setCompulsorySpot(String value) {
        setAttributeInternal(COMPULSORYSPOT, value);
    }

    /**
     * Gets the attribute value for SECTOR using the alias name Sector.
     * @return the SECTOR
     */
    public String getSector() {
        return (String) getAttributeInternal(SECTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for SECTOR using the alias name Sector.
     * @param value value to set the SECTOR
     */
    public void setSector(String value) {
        setAttributeInternal(SECTOR, value);
    }

    /**
     * Gets the attribute value for TICK_VAR using the alias name TickVar.
     * @return the TICK_VAR
     */
    public Integer getTickVar() {
        return (Integer) getAttributeInternal(TICKVAR);
    }

    /**
     * Sets <code>value</code> as attribute value for TICK_VAR using the alias name TickVar.
     * @param value value to set the TICK_VAR
     */
    public void setTickVar(Integer value) {
        setAttributeInternal(TICKVAR, value);
    }

    /**
     * Gets the attribute value for VAR_PERCENT using the alias name VarPercent.
     * @return the VAR_PERCENT
     */
    public Integer getVarPercent() {
        return (Integer) getAttributeInternal(VARPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for VAR_PERCENT using the alias name VarPercent.
     * @param value value to set the VAR_PERCENT
     */
    public void setVarPercent(Integer value) {
        setAttributeInternal(VARPERCENT, value);
    }

    /**
     * Gets the attribute value for ASSET_CLASS using the alias name AssetClass.
     * @return the ASSET_CLASS
     */
    public String getAssetClass() {
        return (String) getAttributeInternal(ASSETCLASS);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_CLASS using the alias name AssetClass.
     * @param value value to set the ASSET_CLASS
     */
    public void setAssetClass(String value) {
        setAttributeInternal(ASSETCLASS, value);
    }

    /**
     * Gets the attribute value for SEQ_NO using the alias name SeqNo.
     * @return the SEQ_NO
     */
    public DBSequence getSeqNo() {
        return (DBSequence)getAttributeInternal(SEQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQ_NO using the alias name SeqNo.
     * @param value value to set the SEQ_NO
     */
    public void setSeqNo(DBSequence value) {
        setAttributeInternal(SEQNO, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
