package leads.capita.trade.model.view;

import oracle.jbo.RowSet;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 14 13:46:10 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProcessErrorVORowImpl extends ViewRowImpl {
    public static final int ENTITY_FILEPROCESSERROR = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ErrType {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getErrType();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setErrType((String)value);
            }
        }
        ,
        ErrorDetail {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getErrorDetail();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setErrorDetail((String)value);
            }
        }
        ,
        EventId {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getEventId();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setEventId((String)value);
            }
        }
        ,
        FileName {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        ImportId {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getImportId();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setImportId((Integer)value);
            }
        }
        ,
        ProcessDate {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getProcessDate();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setProcessDate((Timestamp)value);
            }
        }
        ,
        Remarks {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        RowID {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getRowID();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        FileImportErrorTypeLOV {
            public Object get(FileProcessErrorVORowImpl obj) {
                return obj.getFileImportErrorTypeLOV();
            }

            public void put(FileProcessErrorVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(FileProcessErrorVORowImpl object);

        public abstract void put(FileProcessErrorVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ERRTYPE = AttributesEnum.ErrType.index();
    public static final int ERRORDETAIL = AttributesEnum.ErrorDetail.index();
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int IMPORTID = AttributesEnum.ImportId.index();
    public static final int PROCESSDATE = AttributesEnum.ProcessDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int FILEIMPORTERRORTYPELOV = AttributesEnum.FileImportErrorTypeLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FileProcessErrorVORowImpl() {
    }

    /**
     * Gets FileProcessError entity object.
     * @return the FileProcessError
     */
    public EntityImpl getFileProcessError() {
        return (EntityImpl)getEntity(ENTITY_FILEPROCESSERROR);
    }

    /**
     * Gets the attribute value for ERR_TYPE using the alias name ErrType.
     * @return the ERR_TYPE
     */
    public String getErrType() {
        return (String) getAttributeInternal(ERRTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERR_TYPE using the alias name ErrType.
     * @param value value to set the ERR_TYPE
     */
    public void setErrType(String value) {
        setAttributeInternal(ERRTYPE, value);
    }

    /**
     * Gets the attribute value for ERROR_DETAIL using the alias name ErrorDetail.
     * @return the ERROR_DETAIL
     */
    public String getErrorDetail() {
        return (String) getAttributeInternal(ERRORDETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_DETAIL using the alias name ErrorDetail.
     * @param value value to set the ERROR_DETAIL
     */
    public void setErrorDetail(String value) {
        setAttributeInternal(ERRORDETAIL, value);
    }

    /**
     * Gets the attribute value for EVENT_ID using the alias name EventId.
     * @return the EVENT_ID
     */
    public String getEventId() {
        return (String) getAttributeInternal(EVENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_ID using the alias name EventId.
     * @param value value to set the EVENT_ID
     */
    public void setEventId(String value) {
        setAttributeInternal(EVENTID, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for IMPORT_ID using the alias name ImportId.
     * @return the IMPORT_ID
     */
    public Integer getImportId() {
        return (Integer) getAttributeInternal(IMPORTID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_ID using the alias name ImportId.
     * @param value value to set the IMPORT_ID
     */
    public void setImportId(Integer value) {
        setAttributeInternal(IMPORTID, value);
    }

    /**
     * Gets the attribute value for PROCESS_DATE using the alias name ProcessDate.
     * @return the PROCESS_DATE
     */
    public Timestamp getProcessDate() {
        return (Timestamp) getAttributeInternal(PROCESSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_DATE using the alias name ProcessDate.
     * @param value value to set the PROCESS_DATE
     */
    public void setProcessDate(Timestamp value) {
        setAttributeInternal(PROCESSDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FileImportErrorTypeLOV.
     */
    public RowSet getFileImportErrorTypeLOV() {
        return (RowSet)getAttributeInternal(FILEIMPORTERRORTYPELOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
