package leads.capita.trade.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 14 13:46:10 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProcessErrorVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FileProcessErrorVOImpl() {
    }
}
