package leads.capita.trade.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 20:53:12 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlexTradeDataVORowImpl extends ViewRowImpl {

    public static final int ENTITY_FLEXTRADEDATA = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        FileId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getFileId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setFileId((Long)value);
            }
        }
        ,
        Action {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getAction();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setAction((String)value);
            }
        }
        ,
        Status {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Isin {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getIsin();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setIsin((String)value);
            }
        }
        ,
        Assetclass {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getAssetclass();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setAssetclass((String)value);
            }
        }
        ,
        OrderId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getOrderId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setOrderId((String)value);
            }
        }
        ,
        RefOrderId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getRefOrderId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setRefOrderId((String)value);
            }
        }
        ,
        Side {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getSide();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setSide((String)value);
            }
        }
        ,
        Boid {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getBoid();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setBoid((String)value);
            }
        }
        ,
        SecurityCode {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getSecurityCode();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setSecurityCode((String)value);
            }
        }
        ,
        Board {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getBoard();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setBoard((String)value);
            }
        }
        ,
        FileDate {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getFileDate();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setFileDate((String)value);
            }
        }
        ,
        FileTime {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getFileTime();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setFileTime((String)value);
            }
        }
        ,
        Quantity {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setQuantity((Long)value);
            }
        }
        ,
        Price {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getPrice();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setPrice((BigDecimal)value);
            }
        }
        ,
        TradeValue {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getTradeValue();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setTradeValue((BigDecimal)value);
            }
        }
        ,
        Execid {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getExecid();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setExecid((String)value);
            }
        }
        ,
        SessionId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getSessionId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setSessionId((String)value);
            }
        }
        ,
        FillType {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getFillType();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setFillType((String)value);
            }
        }
        ,
        BranchId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getBranchId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setBranchId((String)value);
            }
        }
        ,
        CompCategory {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getCompCategory();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setCompCategory((String)value);
            }
        }
        ,
        CompulsorySpot {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getCompulsorySpot();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setCompulsorySpot((String)value);
            }
        }
        ,
        ClientCode {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getClientCode();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setClientCode((String)value);
            }
        }
        ,
        TraderDealerId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getTraderDealerId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setTraderDealerId((String)value);
            }
        }
        ,
        OwnerDealerId {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getOwnerDealerId();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setOwnerDealerId((String)value);
            }
        }
        ,
        Tradereporttype {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getTradereporttype();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setTradereporttype((String)value);
            }
        }
        ,
        TradeContractNo {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getTradeContractNo();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setTradeContractNo((String)value);
            }
        }
        ,
        HowlaType {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getHowlaType();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setHowlaType((String)value);
            }
        }
        ,
        ForeignFlag {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getForeignFlag();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setForeignFlag((String)value);
            }
        }
        ,
        SeqNo {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getSeqNo();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setSeqNo((DBSequence)value);
            }
        }
        ,
        FileName {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        Yield {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getYield();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setYield((BigDecimal)value);
            }
        }
        ,
        AccruedInterest {
            public Object get(FlexTradeDataVORowImpl obj) {
                return obj.getAccruedInterest();
            }

            public void put(FlexTradeDataVORowImpl obj, Object value) {
                obj.setAccruedInterest((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(FlexTradeDataVORowImpl object);

        public abstract void put(FlexTradeDataVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int FILEID = AttributesEnum.FileId.index();
    public static final int ACTION = AttributesEnum.Action.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ISIN = AttributesEnum.Isin.index();
    public static final int ASSETCLASS = AttributesEnum.Assetclass.index();
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int REFORDERID = AttributesEnum.RefOrderId.index();
    public static final int SIDE = AttributesEnum.Side.index();
    public static final int BOID = AttributesEnum.Boid.index();
    public static final int SECURITYCODE = AttributesEnum.SecurityCode.index();
    public static final int BOARD = AttributesEnum.Board.index();
    public static final int FILEDATE = AttributesEnum.FileDate.index();
    public static final int FILETIME = AttributesEnum.FileTime.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int TRADEVALUE = AttributesEnum.TradeValue.index();
    public static final int EXECID = AttributesEnum.Execid.index();
    public static final int SESSIONID = AttributesEnum.SessionId.index();
    public static final int FILLTYPE = AttributesEnum.FillType.index();
    public static final int BRANCHID = AttributesEnum.BranchId.index();
    public static final int COMPCATEGORY = AttributesEnum.CompCategory.index();
    public static final int COMPULSORYSPOT = AttributesEnum.CompulsorySpot.index();
    public static final int CLIENTCODE = AttributesEnum.ClientCode.index();
    public static final int TRADERDEALERID = AttributesEnum.TraderDealerId.index();
    public static final int OWNERDEALERID = AttributesEnum.OwnerDealerId.index();
    public static final int TRADEREPORTTYPE = AttributesEnum.Tradereporttype.index();
    public static final int TRADECONTRACTNO = AttributesEnum.TradeContractNo.index();
    public static final int HOWLATYPE = AttributesEnum.HowlaType.index();
    public static final int FOREIGNFLAG = AttributesEnum.ForeignFlag.index();
    public static final int SEQNO = AttributesEnum.SeqNo.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int YIELD = AttributesEnum.Yield.index();
    public static final int ACCRUEDINTEREST = AttributesEnum.AccruedInterest.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FlexTradeDataVORowImpl() {
    }

    /**
     * Gets FlexTradeData entity object.
     * @return the FlexTradeData
     */
    public EntityImpl getFlexTradeData() {
        return (EntityImpl)getEntity(ENTITY_FLEXTRADEDATA);
    }

    /**
     * Gets the attribute value for FILE_ID using the alias name FileId.
     * @return the FILE_ID
     */
    public Long getFileId() {
        return (Long) getAttributeInternal(FILEID);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_ID using the alias name FileId.
     * @param value value to set the FILE_ID
     */
    public void setFileId(Long value) {
        setAttributeInternal(FILEID, value);
    }

    /**
     * Gets the attribute value for ACTION using the alias name Action.
     * @return the ACTION
     */
    public String getAction() {
        return (String) getAttributeInternal(ACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION using the alias name Action.
     * @param value value to set the ACTION
     */
    public void setAction(String value) {
        setAttributeInternal(ACTION, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ISIN using the alias name Isin.
     * @return the ISIN
     */
    public String getIsin() {
        return (String) getAttributeInternal(ISIN);
    }

    /**
     * Sets <code>value</code> as attribute value for ISIN using the alias name Isin.
     * @param value value to set the ISIN
     */
    public void setIsin(String value) {
        setAttributeInternal(ISIN, value);
    }

    /**
     * Gets the attribute value for ASSETCLASS using the alias name Assetclass.
     * @return the ASSETCLASS
     */
    public String getAssetclass() {
        return (String) getAttributeInternal(ASSETCLASS);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSETCLASS using the alias name Assetclass.
     * @param value value to set the ASSETCLASS
     */
    public void setAssetclass(String value) {
        setAttributeInternal(ASSETCLASS, value);
    }

    /**
     * Gets the attribute value for ORDER_ID using the alias name OrderId.
     * @return the ORDER_ID
     */
    public String getOrderId() {
        return (String) getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_ID using the alias name OrderId.
     * @param value value to set the ORDER_ID
     */
    public void setOrderId(String value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for REF_ORDER_ID using the alias name RefOrderId.
     * @return the REF_ORDER_ID
     */
    public String getRefOrderId() {
        return (String) getAttributeInternal(REFORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_ORDER_ID using the alias name RefOrderId.
     * @param value value to set the REF_ORDER_ID
     */
    public void setRefOrderId(String value) {
        setAttributeInternal(REFORDERID, value);
    }

    /**
     * Gets the attribute value for SIDE using the alias name Side.
     * @return the SIDE
     */
    public String getSide() {
        return (String) getAttributeInternal(SIDE);
    }

    /**
     * Sets <code>value</code> as attribute value for SIDE using the alias name Side.
     * @param value value to set the SIDE
     */
    public void setSide(String value) {
        setAttributeInternal(SIDE, value);
    }

    /**
     * Gets the attribute value for BOID using the alias name Boid.
     * @return the BOID
     */
    public String getBoid() {
        return (String) getAttributeInternal(BOID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOID using the alias name Boid.
     * @param value value to set the BOID
     */
    public void setBoid(String value) {
        setAttributeInternal(BOID, value);
    }

    /**
     * Gets the attribute value for SECURITY_CODE using the alias name SecurityCode.
     * @return the SECURITY_CODE
     */
    public String getSecurityCode() {
        return (String) getAttributeInternal(SECURITYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SECURITY_CODE using the alias name SecurityCode.
     * @param value value to set the SECURITY_CODE
     */
    public void setSecurityCode(String value) {
        setAttributeInternal(SECURITYCODE, value);
    }

    /**
     * Gets the attribute value for BOARD using the alias name Board.
     * @return the BOARD
     */
    public String getBoard() {
        return (String) getAttributeInternal(BOARD);
    }

    /**
     * Sets <code>value</code> as attribute value for BOARD using the alias name Board.
     * @param value value to set the BOARD
     */
    public void setBoard(String value) {
        setAttributeInternal(BOARD, value);
    }

    /**
     * Gets the attribute value for FILE_DATE using the alias name FileDate.
     * @return the FILE_DATE
     */
    public String getFileDate() {
        return (String) getAttributeInternal(FILEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_DATE using the alias name FileDate.
     * @param value value to set the FILE_DATE
     */
    public void setFileDate(String value) {
        setAttributeInternal(FILEDATE, value);
    }

    /**
     * Gets the attribute value for FILE_TIME using the alias name FileTime.
     * @return the FILE_TIME
     */
    public String getFileTime() {
        return (String) getAttributeInternal(FILETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_TIME using the alias name FileTime.
     * @param value value to set the FILE_TIME
     */
    public void setFileTime(String value) {
        setAttributeInternal(FILETIME, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Long getQuantity() {
        return (Long) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Long value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public BigDecimal getPrice() {
        return (BigDecimal) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(BigDecimal value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for TRADE_VALUE using the alias name TradeValue.
     * @return the TRADE_VALUE
     */
    public BigDecimal getTradeValue() {
        return (BigDecimal) getAttributeInternal(TRADEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_VALUE using the alias name TradeValue.
     * @param value value to set the TRADE_VALUE
     */
    public void setTradeValue(BigDecimal value) {
        setAttributeInternal(TRADEVALUE, value);
    }

    /**
     * Gets the attribute value for EXECID using the alias name Execid.
     * @return the EXECID
     */
    public String getExecid() {
        return (String) getAttributeInternal(EXECID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXECID using the alias name Execid.
     * @param value value to set the EXECID
     */
    public void setExecid(String value) {
        setAttributeInternal(EXECID, value);
    }

    /**
     * Gets the attribute value for SESSION_ID using the alias name SessionId.
     * @return the SESSION_ID
     */
    public String getSessionId() {
        return (String) getAttributeInternal(SESSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SESSION_ID using the alias name SessionId.
     * @param value value to set the SESSION_ID
     */
    public void setSessionId(String value) {
        setAttributeInternal(SESSIONID, value);
    }

    /**
     * Gets the attribute value for FILL_TYPE using the alias name FillType.
     * @return the FILL_TYPE
     */
    public String getFillType() {
        return (String) getAttributeInternal(FILLTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILL_TYPE using the alias name FillType.
     * @param value value to set the FILL_TYPE
     */
    public void setFillType(String value) {
        setAttributeInternal(FILLTYPE, value);
    }

    /**
     * Gets the attribute value for BRANCH_ID using the alias name BranchId.
     * @return the BRANCH_ID
     */
    public String getBranchId() {
        return (String) getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_ID using the alias name BranchId.
     * @param value value to set the BRANCH_ID
     */
    public void setBranchId(String value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**
     * Gets the attribute value for COMP_CATEGORY using the alias name CompCategory.
     * @return the COMP_CATEGORY
     */
    public String getCompCategory() {
        return (String) getAttributeInternal(COMPCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for COMP_CATEGORY using the alias name CompCategory.
     * @param value value to set the COMP_CATEGORY
     */
    public void setCompCategory(String value) {
        setAttributeInternal(COMPCATEGORY, value);
    }

    /**
     * Gets the attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @return the COMPULSORY_SPOT
     */
    public String getCompulsorySpot() {
        return (String) getAttributeInternal(COMPULSORYSPOT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @param value value to set the COMPULSORY_SPOT
     */
    public void setCompulsorySpot(String value) {
        setAttributeInternal(COMPULSORYSPOT, value);
    }

    /**
     * Gets the attribute value for CLIENT_CODE using the alias name ClientCode.
     * @return the CLIENT_CODE
     */
    public String getClientCode() {
        return (String) getAttributeInternal(CLIENTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_CODE using the alias name ClientCode.
     * @param value value to set the CLIENT_CODE
     */
    public void setClientCode(String value) {
        setAttributeInternal(CLIENTCODE, value);
    }

    /**
     * Gets the attribute value for TRADER_DEALER_ID using the alias name TraderDealerId.
     * @return the TRADER_DEALER_ID
     */
    public String getTraderDealerId() {
        return (String) getAttributeInternal(TRADERDEALERID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADER_DEALER_ID using the alias name TraderDealerId.
     * @param value value to set the TRADER_DEALER_ID
     */
    public void setTraderDealerId(String value) {
        setAttributeInternal(TRADERDEALERID, value);
    }

    /**
     * Gets the attribute value for OWNER_DEALER_ID using the alias name OwnerDealerId.
     * @return the OWNER_DEALER_ID
     */
    public String getOwnerDealerId() {
        return (String) getAttributeInternal(OWNERDEALERID);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER_DEALER_ID using the alias name OwnerDealerId.
     * @param value value to set the OWNER_DEALER_ID
     */
    public void setOwnerDealerId(String value) {
        setAttributeInternal(OWNERDEALERID, value);
    }

    /**
     * Gets the attribute value for TRADEREPORTTYPE using the alias name Tradereporttype.
     * @return the TRADEREPORTTYPE
     */
    public String getTradereporttype() {
        return (String) getAttributeInternal(TRADEREPORTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADEREPORTTYPE using the alias name Tradereporttype.
     * @param value value to set the TRADEREPORTTYPE
     */
    public void setTradereporttype(String value) {
        setAttributeInternal(TRADEREPORTTYPE, value);
    }

    /**
     * Gets the attribute value for TRADE_CONTRACT_NO using the alias name TradeContractNo.
     * @return the TRADE_CONTRACT_NO
     */
    public String getTradeContractNo() {
        return (String) getAttributeInternal(TRADECONTRACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_CONTRACT_NO using the alias name TradeContractNo.
     * @param value value to set the TRADE_CONTRACT_NO
     */
    public void setTradeContractNo(String value) {
        setAttributeInternal(TRADECONTRACTNO, value);
    }

    /**
     * Gets the attribute value for HOWLA_TYPE using the alias name HowlaType.
     * @return the HOWLA_TYPE
     */
    public String getHowlaType() {
        return (String) getAttributeInternal(HOWLATYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOWLA_TYPE using the alias name HowlaType.
     * @param value value to set the HOWLA_TYPE
     */
    public void setHowlaType(String value) {
        setAttributeInternal(HOWLATYPE, value);
    }

    /**
     * Gets the attribute value for FOREIGN_FLAG using the alias name ForeignFlag.
     * @return the FOREIGN_FLAG
     */
    public String getForeignFlag() {
        return (String) getAttributeInternal(FOREIGNFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for FOREIGN_FLAG using the alias name ForeignFlag.
     * @param value value to set the FOREIGN_FLAG
     */
    public void setForeignFlag(String value) {
        setAttributeInternal(FOREIGNFLAG, value);
    }

    /**
     * Gets the attribute value for SEQ_NO using the alias name SeqNo.
     * @return the SEQ_NO
     */
    public DBSequence getSeqNo() {
        return (DBSequence)getAttributeInternal(SEQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQ_NO using the alias name SeqNo.
     * @param value value to set the SEQ_NO
     */
    public void setSeqNo(DBSequence value) {
        setAttributeInternal(SEQNO, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for YIELD using the alias name Yield.
     * @return the YIELD
     */
    public BigDecimal getYield() {
        return (BigDecimal) getAttributeInternal(YIELD);
    }

    /**
     * Sets <code>value</code> as attribute value for YIELD using the alias name Yield.
     * @param value value to set the YIELD
     */
    public void setYield(BigDecimal value) {
        setAttributeInternal(YIELD, value);
    }

    /**
     * Gets the attribute value for ACCRUED_INTEREST using the alias name AccruedInterest.
     * @return the ACCRUED_INTEREST
     */
    public BigDecimal getAccruedInterest() {
        return (BigDecimal) getAttributeInternal(ACCRUEDINTEREST);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCRUED_INTEREST using the alias name AccruedInterest.
     * @param value value to set the ACCRUED_INTEREST
     */
    public void setAccruedInterest(BigDecimal value) {
        setAttributeInternal(ACCRUEDINTEREST, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
