package leads.capita.trade.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 20:53:12 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlexTradeDataVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FlexTradeDataVOImpl() {
    }
}
