package leads.capita.trade.model.view;

import oracle.jbo.RowIterator;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 29 17:57:43 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportExtFilesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_IMPORTEXTFILES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImportId {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getImportId();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setImportId((DBSequence)value);
            }
        }
        ,
        FileId {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getFileId();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setFileId((String)value);
            }
        }
        ,
        FileName {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        FileDate {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getFileDate();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setFileDate((Timestamp)value);
            }
        }
        ,
        TotalRec {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTotalRec();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setTotalRec((Integer)value);
            }
        }
        ,
        ValidateRec {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getValidateRec();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setValidateRec((Integer)value);
            }
        }
        ,
        ErrorRec {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getErrorRec();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setErrorRec((Integer)value);
            }
        }
        ,
        ProcessedRec {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getProcessedRec();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setProcessedRec((Integer)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDt {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getCreationDt();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setCreationDt((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDt {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getLastUpdateDt();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setLastUpdateDt((Timestamp)value);
            }
        }
        ,
        ApprovalStatus {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getApprovalStatus();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setApprovalStatus((String)value);
            }
        }
        ,
        ApprovalRef {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getApprovalRef();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setApprovalRef((String)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setObjectVersionId((Long)value);
            }
        }
        ,
        FileTitle {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getFileTitle();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setFileTitle((String)value);
            }
        }
        ,
        FileProcessErrorVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getFileProcessErrorVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InstrumentPriceVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getInstrumentPriceVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradeFileMsaVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTradeFileMsaVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradeFileMsaPlusVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTradeFileMsaPlusVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradeFileBtVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTradeFileBtVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradePriceFileVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTradePriceFileVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DeletedTradeFileMsaVO {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getDeletedTradeFileMsaVO();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradePriceFileVO1 {
            public Object get(ImportExtFilesVORowImpl obj) {
                return obj.getTradePriceFileVO1();
            }

            public void put(ImportExtFilesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ImportExtFilesVORowImpl object);

        public abstract void put(ImportExtFilesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPORTID = AttributesEnum.ImportId.index();
    public static final int FILEID = AttributesEnum.FileId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int FILEDATE = AttributesEnum.FileDate.index();
    public static final int TOTALREC = AttributesEnum.TotalRec.index();
    public static final int VALIDATEREC = AttributesEnum.ValidateRec.index();
    public static final int ERRORREC = AttributesEnum.ErrorRec.index();
    public static final int PROCESSEDREC = AttributesEnum.ProcessedRec.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDT = AttributesEnum.CreationDt.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDT = AttributesEnum.LastUpdateDt.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int APPROVALREF = AttributesEnum.ApprovalRef.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int FILETITLE = AttributesEnum.FileTitle.index();
    public static final int FILEPROCESSERRORVO = AttributesEnum.FileProcessErrorVO.index();
    public static final int INSTRUMENTPRICEVO = AttributesEnum.InstrumentPriceVO.index();
    public static final int TRADEFILEMSAVO = AttributesEnum.TradeFileMsaVO.index();
    public static final int TRADEFILEMSAPLUSVO = AttributesEnum.TradeFileMsaPlusVO.index();
    public static final int TRADEFILEBTVO = AttributesEnum.TradeFileBtVO.index();
    public static final int TRADEPRICEFILEVO = AttributesEnum.TradePriceFileVO.index();
    public static final int DELETEDTRADEFILEMSAVO = AttributesEnum.DeletedTradeFileMsaVO.index();
    public static final int TRADEPRICEFILEVO1 = AttributesEnum.TradePriceFileVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImportExtFilesVORowImpl() {
    }

    /**
     * Gets ImportExtFiles entity object.
     * @return the ImportExtFiles
     */
    public EntityImpl getImportExtFiles() {
        return (EntityImpl)getEntity(ENTITY_IMPORTEXTFILES);
    }

    /**
     * Gets the attribute value for IMPORT_ID using the alias name ImportId.
     * @return the IMPORT_ID
     */
    public DBSequence getImportId() {
        return (DBSequence)getAttributeInternal(IMPORTID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_ID using the alias name ImportId.
     * @param value value to set the IMPORT_ID
     */
    public void setImportId(DBSequence value) {
        setAttributeInternal(IMPORTID, value);
    }

    /**
     * Gets the attribute value for FILE_ID using the alias name FileId.
     * @return the FILE_ID
     */
    public String getFileId() {
        return (String)getAttributeInternal(FILEID);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_ID using the alias name FileId.
     * @param value value to set the FILE_ID
     */
    public void setFileId(String value) {
        setAttributeInternal(FILEID, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String)getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for FILE_DATE using the alias name FileDate.
     * @return the FILE_DATE
     */
    public Timestamp getFileDate() {
        return (Timestamp)getAttributeInternal(FILEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_DATE using the alias name FileDate.
     * @param value value to set the FILE_DATE
     */
    public void setFileDate(Timestamp value) {
        setAttributeInternal(FILEDATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_REC using the alias name TotalRec.
     * @return the TOTAL_REC
     */
    public Integer getTotalRec() {
        return (Integer)getAttributeInternal(TOTALREC);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_REC using the alias name TotalRec.
     * @param value value to set the TOTAL_REC
     */
    public void setTotalRec(Integer value) {
        setAttributeInternal(TOTALREC, value);
    }

    /**
     * Gets the attribute value for VALIDATE_REC using the alias name ValidateRec.
     * @return the VALIDATE_REC
     */
    public Integer getValidateRec() {
        return (Integer)getAttributeInternal(VALIDATEREC);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATE_REC using the alias name ValidateRec.
     * @param value value to set the VALIDATE_REC
     */
    public void setValidateRec(Integer value) {
        setAttributeInternal(VALIDATEREC, value);
    }

    /**
     * Gets the attribute value for ERROR_REC using the alias name ErrorRec.
     * @return the ERROR_REC
     */
    public Integer getErrorRec() {
        return (Integer)getAttributeInternal(ERRORREC);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_REC using the alias name ErrorRec.
     * @param value value to set the ERROR_REC
     */
    public void setErrorRec(Integer value) {
        setAttributeInternal(ERRORREC, value);
    }

    /**
     * Gets the attribute value for PROCESSED_REC using the alias name ProcessedRec.
     * @return the PROCESSED_REC
     */
    public Integer getProcessedRec() {
        return (Integer)getAttributeInternal(PROCESSEDREC);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESSED_REC using the alias name ProcessedRec.
     * @param value value to set the PROCESSED_REC
     */
    public void setProcessedRec(Integer value) {
        setAttributeInternal(PROCESSEDREC, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DT using the alias name CreationDt.
     * @return the CREATION_DT
     */
    public Timestamp getCreationDt() {
        return (Timestamp)getAttributeInternal(CREATIONDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DT using the alias name CreationDt.
     * @param value value to set the CREATION_DT
     */
    public void setCreationDt(Timestamp value) {
        setAttributeInternal(CREATIONDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DT using the alias name LastUpdateDt.
     * @return the LAST_UPDATE_DT
     */
    public Timestamp getLastUpdateDt() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DT using the alias name LastUpdateDt.
     * @param value value to set the LAST_UPDATE_DT
     */
    public void setLastUpdateDt(Timestamp value) {
        setAttributeInternal(LASTUPDATEDT, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String)getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for APPROVAL_REF using the alias name ApprovalRef.
     * @return the APPROVAL_REF
     */
    public String getApprovalRef() {
        return (String)getAttributeInternal(APPROVALREF);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_REF using the alias name ApprovalRef.
     * @param value value to set the APPROVAL_REF
     */
    public void setApprovalRef(String value) {
        setAttributeInternal(APPROVALREF, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return the OBJECT_VERSION_ID
     */
    public Long getObjectVersionId() {
        return (Long)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Long value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FileTitle.
     * @return the FileTitle
     */
    public String getFileTitle() {
        return (String)getAttributeInternal(FILETITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FileTitle.
     * @param value value to set the  FileTitle
     */
    public void setFileTitle(String value) {
        setAttributeInternal(FILETITLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FileProcessErrorVO.
     */
    public RowIterator getFileProcessErrorVO() {
        return (RowIterator)getAttributeInternal(FILEPROCESSERRORVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InstrumentPriceVO.
     */
    public RowIterator getInstrumentPriceVO() {
        return (RowIterator)getAttributeInternal(INSTRUMENTPRICEVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TradeFileMsaVO.
     */
    public RowIterator getTradeFileMsaVO() {
        return (RowIterator)getAttributeInternal(TRADEFILEMSAVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TradeFileMsaPlusVO.
     */
    public RowIterator getTradeFileMsaPlusVO() {
        return (RowIterator)getAttributeInternal(TRADEFILEMSAPLUSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TradeFileBtVO.
     */
    public RowIterator getTradeFileBtVO() {
        return (RowIterator)getAttributeInternal(TRADEFILEBTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TradePriceFileVO.
     */
    public RowIterator getTradePriceFileVO() {
        return (RowIterator)getAttributeInternal(TRADEPRICEFILEVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DeletedTradeFileMsaVO.
     */
    public RowIterator getDeletedTradeFileMsaVO() {
        return (RowIterator)getAttributeInternal(DELETEDTRADEFILEMSAVO);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TradePriceFileVO1.
     */
    public RowIterator getTradePriceFileVO1() {
        return (RowIterator)getAttributeInternal(TRADEPRICEFILEVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
