package leads.capita.trade.model.view;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 29 17:49:01 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InstrumentsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        InstrumentId {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getInstrumentId();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setInstrumentId((Integer)value);
            }
        }
        ,
        InstrumentName {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getInstrumentName();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setInstrumentName((String)value);
            }
        }
        ,
        InstrumentType {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getInstrumentType();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setInstrumentType((String)value);
            }
        }
        ,
        ShortName {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getShortName();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setShortName((String)value);
            }
        }
        ,
        CompanyId {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCompanyId();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCompanyId((Integer)value);
            }
        }
        ,
        InstrumentGroup {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getInstrumentGroup();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setInstrumentGroup((String)value);
            }
        }
        ,
        Sector {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getSector();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setSector((String)value);
            }
        }
        ,
        Industry {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getIndustry();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setIndustry((String)value);
            }
        }
        ,
        Isin {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getIsin();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setIsin((String)value);
            }
        }
        ,
        FaceValue {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getFaceValue();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setFaceValue((BigDecimal)value);
            }
        }
        ,
        BookValue {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getBookValue();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setBookValue((BigDecimal)value);
            }
        }
        ,
        NoOfShare {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getNoOfShare();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setNoOfShare((Long)value);
            }
        }
        ,
        LotSize {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getLotSize();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setLotSize((Integer)value);
            }
        }
        ,
        TickSize {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getTickSize();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setTickSize((BigDecimal)value);
            }
        }
        ,
        ValuationType {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getValuationType();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setValuationType((String)value);
            }
        }
        ,
        ValuationAmt {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getValuationAmt();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setValuationAmt((BigDecimal)value);
            }
        }
        ,
        Existence {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getExistence();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setExistence((String)value);
            }
        }
        ,
        Status {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDt {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCreationDt();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCreationDt((Timestamp)value);
            }
        }
        ,
        ApprovedBy {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getApprovedBy();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setApprovedBy((String)value);
            }
        }
        ,
        ApproveDt {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getApproveDt();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setApproveDt((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDt {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getLastUpdateDt();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setLastUpdateDt((Timestamp)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setObjectVersionId((Long)value);
            }
        }
        ,
        ApprovalStatus {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getApprovalStatus();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setApprovalStatus((String)value);
            }
        }
        ,
        IsNetable {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getIsNetable();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setIsNetable((String)value);
            }
        }
        ,
        MarketPrice {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getMarketPrice();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setMarketPrice((BigDecimal)value);
            }
        }
        ,
        CurrentMarket {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCurrentMarket();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCurrentMarket((String)value);
            }
        }
        ,
        ManualSattlement {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getManualSattlement();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setManualSattlement((String)value);
            }
        }
        ,
        IstradingApprove {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getIstradingApprove();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setIstradingApprove((String)value);
            }
        }
        ,
        Marginable {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getMarginable();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setMarginable((String)value);
            }
        }
        ,
        SessionId {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getSessionId();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setSessionId((Integer)value);
            }
        }
        ,
        SectorRefCode {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getSectorRefCode();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setSectorRefCode((String)value);
            }
        }
        ,
        IndustryRefCode {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getIndustryRefCode();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setIndustryRefCode((String)value);
            }
        }
        ,
        Nav {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getNav();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setNav((BigDecimal)value);
            }
        }
        ,
        Eps {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getEps();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setEps((BigDecimal)value);
            }
        }
        ,
        PERatio {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getPERatio();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setPERatio((Integer)value);
            }
        }
        ,
        CompanyCd {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCompanyCd();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCompanyCd((BigInteger)value);
            }
        }
        ,
        CompanyCode {
            public Object get(InstrumentsVORowImpl obj) {
                return obj.getCompanyCode();
            }

            public void put(InstrumentsVORowImpl obj, Object value) {
                obj.setCompanyCode((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InstrumentsVORowImpl object);

        public abstract void put(InstrumentsVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int INSTRUMENTID = AttributesEnum.InstrumentId.index();
    public static final int INSTRUMENTNAME = AttributesEnum.InstrumentName.index();
    public static final int INSTRUMENTTYPE = AttributesEnum.InstrumentType.index();
    public static final int SHORTNAME = AttributesEnum.ShortName.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int INSTRUMENTGROUP = AttributesEnum.InstrumentGroup.index();
    public static final int SECTOR = AttributesEnum.Sector.index();
    public static final int INDUSTRY = AttributesEnum.Industry.index();
    public static final int ISIN = AttributesEnum.Isin.index();
    public static final int FACEVALUE = AttributesEnum.FaceValue.index();
    public static final int BOOKVALUE = AttributesEnum.BookValue.index();
    public static final int NOOFSHARE = AttributesEnum.NoOfShare.index();
    public static final int LOTSIZE = AttributesEnum.LotSize.index();
    public static final int TICKSIZE = AttributesEnum.TickSize.index();
    public static final int VALUATIONTYPE = AttributesEnum.ValuationType.index();
    public static final int VALUATIONAMT = AttributesEnum.ValuationAmt.index();
    public static final int EXISTENCE = AttributesEnum.Existence.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDT = AttributesEnum.CreationDt.index();
    public static final int APPROVEDBY = AttributesEnum.ApprovedBy.index();
    public static final int APPROVEDT = AttributesEnum.ApproveDt.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDT = AttributesEnum.LastUpdateDt.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int ISNETABLE = AttributesEnum.IsNetable.index();
    public static final int MARKETPRICE = AttributesEnum.MarketPrice.index();
    public static final int CURRENTMARKET = AttributesEnum.CurrentMarket.index();
    public static final int MANUALSATTLEMENT = AttributesEnum.ManualSattlement.index();
    public static final int ISTRADINGAPPROVE = AttributesEnum.IstradingApprove.index();
    public static final int MARGINABLE = AttributesEnum.Marginable.index();
    public static final int SESSIONID = AttributesEnum.SessionId.index();
    public static final int SECTORREFCODE = AttributesEnum.SectorRefCode.index();
    public static final int INDUSTRYREFCODE = AttributesEnum.IndustryRefCode.index();
    public static final int NAV = AttributesEnum.Nav.index();
    public static final int EPS = AttributesEnum.Eps.index();
    public static final int PERATIO = AttributesEnum.PERatio.index();
    public static final int COMPANYCD = AttributesEnum.CompanyCd.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InstrumentsVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute InstrumentId.
     * @return the InstrumentId
     */
    public Integer getInstrumentId() {
        return (Integer) getAttributeInternal(INSTRUMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InstrumentId.
     * @param value value to set the  InstrumentId
     */
    public void setInstrumentId(Integer value) {
        setAttributeInternal(INSTRUMENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InstrumentName.
     * @return the InstrumentName
     */
    public String getInstrumentName() {
        return (String) getAttributeInternal(INSTRUMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InstrumentName.
     * @param value value to set the  InstrumentName
     */
    public void setInstrumentName(String value) {
        setAttributeInternal(INSTRUMENTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InstrumentType.
     * @return the InstrumentType
     */
    public String getInstrumentType() {
        return (String) getAttributeInternal(INSTRUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InstrumentType.
     * @param value value to set the  InstrumentType
     */
    public void setInstrumentType(String value) {
        setAttributeInternal(INSTRUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShortName.
     * @return the ShortName
     */
    public String getShortName() {
        return (String) getAttributeInternal(SHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShortName.
     * @param value value to set the  ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyId.
     * @return the CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyId.
     * @param value value to set the  CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InstrumentGroup.
     * @return the InstrumentGroup
     */
    public String getInstrumentGroup() {
        return (String) getAttributeInternal(INSTRUMENTGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InstrumentGroup.
     * @param value value to set the  InstrumentGroup
     */
    public void setInstrumentGroup(String value) {
        setAttributeInternal(INSTRUMENTGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Sector.
     * @return the Sector
     */
    public String getSector() {
        return (String) getAttributeInternal(SECTOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Sector.
     * @param value value to set the  Sector
     */
    public void setSector(String value) {
        setAttributeInternal(SECTOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Industry.
     * @return the Industry
     */
    public String getIndustry() {
        return (String) getAttributeInternal(INDUSTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Industry.
     * @param value value to set the  Industry
     */
    public void setIndustry(String value) {
        setAttributeInternal(INDUSTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Isin.
     * @return the Isin
     */
    public String getIsin() {
        return (String) getAttributeInternal(ISIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Isin.
     * @param value value to set the  Isin
     */
    public void setIsin(String value) {
        setAttributeInternal(ISIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FaceValue.
     * @return the FaceValue
     */
    public BigDecimal getFaceValue() {
        return (BigDecimal) getAttributeInternal(FACEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FaceValue.
     * @param value value to set the  FaceValue
     */
    public void setFaceValue(BigDecimal value) {
        setAttributeInternal(FACEVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BookValue.
     * @return the BookValue
     */
    public BigDecimal getBookValue() {
        return (BigDecimal) getAttributeInternal(BOOKVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BookValue.
     * @param value value to set the  BookValue
     */
    public void setBookValue(BigDecimal value) {
        setAttributeInternal(BOOKVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoOfShare.
     * @return the NoOfShare
     */
    public Long getNoOfShare() {
        return (Long) getAttributeInternal(NOOFSHARE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoOfShare.
     * @param value value to set the  NoOfShare
     */
    public void setNoOfShare(Long value) {
        setAttributeInternal(NOOFSHARE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LotSize.
     * @return the LotSize
     */
    public Integer getLotSize() {
        return (Integer) getAttributeInternal(LOTSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LotSize.
     * @param value value to set the  LotSize
     */
    public void setLotSize(Integer value) {
        setAttributeInternal(LOTSIZE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TickSize.
     * @return the TickSize
     */
    public BigDecimal getTickSize() {
        return (BigDecimal) getAttributeInternal(TICKSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TickSize.
     * @param value value to set the  TickSize
     */
    public void setTickSize(BigDecimal value) {
        setAttributeInternal(TICKSIZE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValuationType.
     * @return the ValuationType
     */
    public String getValuationType() {
        return (String) getAttributeInternal(VALUATIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValuationType.
     * @param value value to set the  ValuationType
     */
    public void setValuationType(String value) {
        setAttributeInternal(VALUATIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValuationAmt.
     * @return the ValuationAmt
     */
    public BigDecimal getValuationAmt() {
        return (BigDecimal) getAttributeInternal(VALUATIONAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValuationAmt.
     * @param value value to set the  ValuationAmt
     */
    public void setValuationAmt(BigDecimal value) {
        setAttributeInternal(VALUATIONAMT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Existence.
     * @return the Existence
     */
    public String getExistence() {
        return (String) getAttributeInternal(EXISTENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Existence.
     * @param value value to set the  Existence
     */
    public void setExistence(String value) {
        setAttributeInternal(EXISTENCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDt.
     * @return the CreationDt
     */
    public Timestamp getCreationDt() {
        return (Timestamp) getAttributeInternal(CREATIONDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDt.
     * @param value value to set the  CreationDt
     */
    public void setCreationDt(Timestamp value) {
        setAttributeInternal(CREATIONDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovedBy.
     * @return the ApprovedBy
     */
    public String getApprovedBy() {
        return (String) getAttributeInternal(APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovedBy.
     * @param value value to set the  ApprovedBy
     */
    public void setApprovedBy(String value) {
        setAttributeInternal(APPROVEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApproveDt.
     * @return the ApproveDt
     */
    public Timestamp getApproveDt() {
        return (Timestamp) getAttributeInternal(APPROVEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApproveDt.
     * @param value value to set the  ApproveDt
     */
    public void setApproveDt(Timestamp value) {
        setAttributeInternal(APPROVEDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDt.
     * @return the LastUpdateDt
     */
    public Timestamp getLastUpdateDt() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDt.
     * @param value value to set the  LastUpdateDt
     */
    public void setLastUpdateDt(Timestamp value) {
        setAttributeInternal(LASTUPDATEDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Long getObjectVersionId() {
        return (Long) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionId.
     * @param value value to set the  ObjectVersionId
     */
    public void setObjectVersionId(Long value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovalStatus.
     * @return the ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovalStatus.
     * @param value value to set the  ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsNetable.
     * @return the IsNetable
     */
    public String getIsNetable() {
        return (String) getAttributeInternal(ISNETABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsNetable.
     * @param value value to set the  IsNetable
     */
    public void setIsNetable(String value) {
        setAttributeInternal(ISNETABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MarketPrice.
     * @return the MarketPrice
     */
    public BigDecimal getMarketPrice() {
        return (BigDecimal) getAttributeInternal(MARKETPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MarketPrice.
     * @param value value to set the  MarketPrice
     */
    public void setMarketPrice(BigDecimal value) {
        setAttributeInternal(MARKETPRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentMarket.
     * @return the CurrentMarket
     */
    public String getCurrentMarket() {
        return (String) getAttributeInternal(CURRENTMARKET);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentMarket.
     * @param value value to set the  CurrentMarket
     */
    public void setCurrentMarket(String value) {
        setAttributeInternal(CURRENTMARKET, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ManualSattlement.
     * @return the ManualSattlement
     */
    public String getManualSattlement() {
        return (String) getAttributeInternal(MANUALSATTLEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ManualSattlement.
     * @param value value to set the  ManualSattlement
     */
    public void setManualSattlement(String value) {
        setAttributeInternal(MANUALSATTLEMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IstradingApprove.
     * @return the IstradingApprove
     */
    public String getIstradingApprove() {
        return (String) getAttributeInternal(ISTRADINGAPPROVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IstradingApprove.
     * @param value value to set the  IstradingApprove
     */
    public void setIstradingApprove(String value) {
        setAttributeInternal(ISTRADINGAPPROVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Marginable.
     * @return the Marginable
     */
    public String getMarginable() {
        return (String) getAttributeInternal(MARGINABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Marginable.
     * @param value value to set the  Marginable
     */
    public void setMarginable(String value) {
        setAttributeInternal(MARGINABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SessionId.
     * @return the SessionId
     */
    public Integer getSessionId() {
        return (Integer) getAttributeInternal(SESSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SessionId.
     * @param value value to set the  SessionId
     */
    public void setSessionId(Integer value) {
        setAttributeInternal(SESSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SectorRefCode.
     * @return the SectorRefCode
     */
    public String getSectorRefCode() {
        return (String) getAttributeInternal(SECTORREFCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SectorRefCode.
     * @param value value to set the  SectorRefCode
     */
    public void setSectorRefCode(String value) {
        setAttributeInternal(SECTORREFCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IndustryRefCode.
     * @return the IndustryRefCode
     */
    public String getIndustryRefCode() {
        return (String) getAttributeInternal(INDUSTRYREFCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IndustryRefCode.
     * @param value value to set the  IndustryRefCode
     */
    public void setIndustryRefCode(String value) {
        setAttributeInternal(INDUSTRYREFCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nav.
     * @return the Nav
     */
    public BigDecimal getNav() {
        return (BigDecimal) getAttributeInternal(NAV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nav.
     * @param value value to set the  Nav
     */
    public void setNav(BigDecimal value) {
        setAttributeInternal(NAV, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Eps.
     * @return the Eps
     */
    public BigDecimal getEps() {
        return (BigDecimal) getAttributeInternal(EPS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Eps.
     * @param value value to set the  Eps
     */
    public void setEps(BigDecimal value) {
        setAttributeInternal(EPS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PERatio.
     * @return the PERatio
     */
    public Integer getPERatio() {
        return (Integer) getAttributeInternal(PERATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PERatio.
     * @param value value to set the  PERatio
     */
    public void setPERatio(Integer value) {
        setAttributeInternal(PERATIO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyCd.
     * @return the CompanyCd
     */
    public BigInteger getCompanyCd() {
        return (BigInteger) getAttributeInternal(COMPANYCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyCd.
     * @param value value to set the  CompanyCd
     */
    public void setCompanyCd(BigInteger value) {
        setAttributeInternal(COMPANYCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyCode.
     * @return the CompanyCode
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyCode.
     * @param value value to set the  CompanyCode
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
