package leads.capita.trade.model.view;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 12 13:13:45 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvestorAccountsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AccountId {
            public Object get(InvestorAccountsVORowImpl obj) {
                return obj.getAccountId();
            }

            public void put(InvestorAccountsVORowImpl obj, Object value) {
                obj.setAccountId((Long)value);
            }
        }
        ,
        InvestorCode {
            public Object get(InvestorAccountsVORowImpl obj) {
                return obj.getInvestorCode();
            }

            public void put(InvestorAccountsVORowImpl obj, Object value) {
                obj.setInvestorCode((String)value);
            }
        }
        ,
        Name {
            public Object get(InvestorAccountsVORowImpl obj) {
                return obj.getName();
            }

            public void put(InvestorAccountsVORowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        ProductId {
            public Object get(InvestorAccountsVORowImpl obj) {
                return obj.getProductId();
            }

            public void put(InvestorAccountsVORowImpl obj, Object value) {
                obj.setProductId((Integer)value);
            }
        }
        ,
        Boid {
            public Object get(InvestorAccountsVORowImpl obj) {
                return obj.getBoid();
            }

            public void put(InvestorAccountsVORowImpl obj, Object value) {
                obj.setBoid((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InvestorAccountsVORowImpl object);

        public abstract void put(InvestorAccountsVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ACCOUNTID = AttributesEnum.AccountId.index();
    public static final int INVESTORCODE = AttributesEnum.InvestorCode.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int BOID = AttributesEnum.Boid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvestorAccountsVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute AccountId.
     * @return the AccountId
     */
    public Long getAccountId() {
        return (Long) getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AccountId.
     * @param value value to set the  AccountId
     */
    public void setAccountId(Long value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvestorCode.
     * @return the InvestorCode
     */
    public String getInvestorCode() {
        return (String) getAttributeInternal(INVESTORCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvestorCode.
     * @param value value to set the  InvestorCode
     */
    public void setInvestorCode(String value) {
        setAttributeInternal(INVESTORCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductId.
     * @return the ProductId
     */
    public Integer getProductId() {
        return (Integer) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductId.
     * @param value value to set the  ProductId
     */
    public void setProductId(Integer value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Boid.
     * @return the Boid
     */
    public String getBoid() {
        return (String) getAttributeInternal(BOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Boid.
     * @param value value to set the  Boid
     */
    public void setBoid(String value) {
        setAttributeInternal(BOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
