package leads.capita.trade.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 16:18:16 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TRADES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AccountId {
            public Object get(TradesVORowImpl obj) {
                return obj.getAccountId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setAccountId((Long)value);
            }
        }
        ,
        AitCharge {
            public Object get(TradesVORowImpl obj) {
                return obj.getAitCharge();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setAitCharge((BigDecimal)value);
            }
        }
        ,
        BrokerComRate {
            public Object get(TradesVORowImpl obj) {
                return obj.getBrokerComRate();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setBrokerComRate((BigDecimal)value);
            }
        }
        ,
        BrokerId {
            public Object get(TradesVORowImpl obj) {
                return obj.getBrokerId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setBrokerId((Integer)value);
            }
        }
        ,
        BuySell {
            public Object get(TradesVORowImpl obj) {
                return obj.getBuySell();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setBuySell((String)value);
            }
        }
        ,
        ClientComRate {
            public Object get(TradesVORowImpl obj) {
                return obj.getClientComRate();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setClientComRate((BigDecimal)value);
            }
        }
        ,
        Commission {
            public Object get(TradesVORowImpl obj) {
                return obj.getCommission();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setCommission((BigDecimal)value);
            }
        }
        ,
        CompulsorySpot {
            public Object get(TradesVORowImpl obj) {
                return obj.getCompulsorySpot();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setCompulsorySpot((String)value);
            }
        }
        ,
        ContractNo {
            public Object get(TradesVORowImpl obj) {
                return obj.getContractNo();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setContractNo((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(TradesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDt {
            public Object get(TradesVORowImpl obj) {
                return obj.getCreationDt();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setCreationDt((Timestamp)value);
            }
        }
        ,
        ExchangeId {
            public Object get(TradesVORowImpl obj) {
                return obj.getExchangeId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setExchangeId((Integer)value);
            }
        }
        ,
        HowlaCharge {
            public Object get(TradesVORowImpl obj) {
                return obj.getHowlaCharge();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setHowlaCharge((BigDecimal)value);
            }
        }
        ,
        HowlaType {
            public Object get(TradesVORowImpl obj) {
                return obj.getHowlaType();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setHowlaType((String)value);
            }
        }
        ,
        ImportFileId {
            public Object get(TradesVORowImpl obj) {
                return obj.getImportFileId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setImportFileId((Integer)value);
            }
        }
        ,
        InstrumentCode {
            public Object get(TradesVORowImpl obj) {
                return obj.getInstrumentCode();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setInstrumentCode((String)value);
            }
        }
        ,
        InstrumentGroup {
            public Object get(TradesVORowImpl obj) {
                return obj.getInstrumentGroup();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setInstrumentGroup((String)value);
            }
        }
        ,
        InstrumentId {
            public Object get(TradesVORowImpl obj) {
                return obj.getInstrumentId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setInstrumentId((Integer)value);
            }
        }
        ,
        InvestorCode {
            public Object get(TradesVORowImpl obj) {
                return obj.getInvestorCode();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setInvestorCode((String)value);
            }
        }
        ,
        IsBda {
            public Object get(TradesVORowImpl obj) {
                return obj.getIsBda();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setIsBda((String)value);
            }
        }
        ,
        IsForeign {
            public Object get(TradesVORowImpl obj) {
                return obj.getIsForeign();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setIsForeign((String)value);
            }
        }
        ,
        LagaCharge {
            public Object get(TradesVORowImpl obj) {
                return obj.getLagaCharge();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setLagaCharge((BigDecimal)value);
            }
        }
        ,
        MarketType {
            public Object get(TradesVORowImpl obj) {
                return obj.getMarketType();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setMarketType((String)value);
            }
        }
        ,
        MbankId {
            public Object get(TradesVORowImpl obj) {
                return obj.getMbankId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setMbankId((Integer)value);
            }
        }
        ,
        NewCommRate {
            public Object get(TradesVORowImpl obj) {
                return obj.getNewCommRate();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setNewCommRate((BigDecimal)value);
            }
        }
        ,
        OrgBranchId {
            public Object get(TradesVORowImpl obj) {
                return obj.getOrgBranchId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setOrgBranchId((Integer)value);
            }
        }
        ,
        Price {
            public Object get(TradesVORowImpl obj) {
                return obj.getPrice();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setPrice((BigDecimal)value);
            }
        }
        ,
        ProductId {
            public Object get(TradesVORowImpl obj) {
                return obj.getProductId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setProductId((Integer)value);
            }
        }
        ,
        Quantity {
            public Object get(TradesVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setQuantity((Long)value);
            }
        }
        ,
        Status {
            public Object get(TradesVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TracerNo {
            public Object get(TradesVORowImpl obj) {
                return obj.getTracerNo();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setTracerNo((Integer)value);
            }
        }
        ,
        TradeId {
            public Object get(TradesVORowImpl obj) {
                return obj.getTradeId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setTradeId((Integer)value);
            }
        }
        ,
        TradeTime {
            public Object get(TradesVORowImpl obj) {
                return obj.getTradeTime();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setTradeTime((String)value);
            }
        }
        ,
        TraderId {
            public Object get(TradesVORowImpl obj) {
                return obj.getTraderId();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setTraderId((String)value);
            }
        }
        ,
        TradingDate {
            public Object get(TradesVORowImpl obj) {
                return obj.getTradingDate();
            }

            public void put(TradesVORowImpl obj, Object value) {
                obj.setTradingDate((Timestamp)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TradesVORowImpl object);

        public abstract void put(TradesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACCOUNTID = AttributesEnum.AccountId.index();
    public static final int AITCHARGE = AttributesEnum.AitCharge.index();
    public static final int BROKERCOMRATE = AttributesEnum.BrokerComRate.index();
    public static final int BROKERID = AttributesEnum.BrokerId.index();
    public static final int BUYSELL = AttributesEnum.BuySell.index();
    public static final int CLIENTCOMRATE = AttributesEnum.ClientComRate.index();
    public static final int COMMISSION = AttributesEnum.Commission.index();
    public static final int COMPULSORYSPOT = AttributesEnum.CompulsorySpot.index();
    public static final int CONTRACTNO = AttributesEnum.ContractNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDT = AttributesEnum.CreationDt.index();
    public static final int EXCHANGEID = AttributesEnum.ExchangeId.index();
    public static final int HOWLACHARGE = AttributesEnum.HowlaCharge.index();
    public static final int HOWLATYPE = AttributesEnum.HowlaType.index();
    public static final int IMPORTFILEID = AttributesEnum.ImportFileId.index();
    public static final int INSTRUMENTCODE = AttributesEnum.InstrumentCode.index();
    public static final int INSTRUMENTGROUP = AttributesEnum.InstrumentGroup.index();
    public static final int INSTRUMENTID = AttributesEnum.InstrumentId.index();
    public static final int INVESTORCODE = AttributesEnum.InvestorCode.index();
    public static final int ISBDA = AttributesEnum.IsBda.index();
    public static final int ISFOREIGN = AttributesEnum.IsForeign.index();
    public static final int LAGACHARGE = AttributesEnum.LagaCharge.index();
    public static final int MARKETTYPE = AttributesEnum.MarketType.index();
    public static final int MBANKID = AttributesEnum.MbankId.index();
    public static final int NEWCOMMRATE = AttributesEnum.NewCommRate.index();
    public static final int ORGBRANCHID = AttributesEnum.OrgBranchId.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TRACERNO = AttributesEnum.TracerNo.index();
    public static final int TRADEID = AttributesEnum.TradeId.index();
    public static final int TRADETIME = AttributesEnum.TradeTime.index();
    public static final int TRADERID = AttributesEnum.TraderId.index();
    public static final int TRADINGDATE = AttributesEnum.TradingDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TradesVORowImpl() {
    }

    /**
     * Gets Trades entity object.
     * @return the Trades
     */
    public EntityImpl getTrades() {
        return (EntityImpl)getEntity(ENTITY_TRADES);
    }

    /**
     * Gets the attribute value for ACCOUNT_ID using the alias name AccountId.
     * @return the ACCOUNT_ID
     */
    public Long getAccountId() {
        return (Long) getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_ID using the alias name AccountId.
     * @param value value to set the ACCOUNT_ID
     */
    public void setAccountId(Long value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for AIT_CHARGE using the alias name AitCharge.
     * @return the AIT_CHARGE
     */
    public BigDecimal getAitCharge() {
        return (BigDecimal) getAttributeInternal(AITCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for AIT_CHARGE using the alias name AitCharge.
     * @param value value to set the AIT_CHARGE
     */
    public void setAitCharge(BigDecimal value) {
        setAttributeInternal(AITCHARGE, value);
    }

    /**
     * Gets the attribute value for BROKER_COM_RATE using the alias name BrokerComRate.
     * @return the BROKER_COM_RATE
     */
    public BigDecimal getBrokerComRate() {
        return (BigDecimal) getAttributeInternal(BROKERCOMRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BROKER_COM_RATE using the alias name BrokerComRate.
     * @param value value to set the BROKER_COM_RATE
     */
    public void setBrokerComRate(BigDecimal value) {
        setAttributeInternal(BROKERCOMRATE, value);
    }

    /**
     * Gets the attribute value for BROKER_ID using the alias name BrokerId.
     * @return the BROKER_ID
     */
    public Integer getBrokerId() {
        return (Integer) getAttributeInternal(BROKERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BROKER_ID using the alias name BrokerId.
     * @param value value to set the BROKER_ID
     */
    public void setBrokerId(Integer value) {
        setAttributeInternal(BROKERID, value);
    }

    /**
     * Gets the attribute value for BUY_SELL using the alias name BuySell.
     * @return the BUY_SELL
     */
    public String getBuySell() {
        return (String) getAttributeInternal(BUYSELL);
    }

    /**
     * Sets <code>value</code> as attribute value for BUY_SELL using the alias name BuySell.
     * @param value value to set the BUY_SELL
     */
    public void setBuySell(String value) {
        setAttributeInternal(BUYSELL, value);
    }

    /**
     * Gets the attribute value for CLIENT_COM_RATE using the alias name ClientComRate.
     * @return the CLIENT_COM_RATE
     */
    public BigDecimal getClientComRate() {
        return (BigDecimal) getAttributeInternal(CLIENTCOMRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_COM_RATE using the alias name ClientComRate.
     * @param value value to set the CLIENT_COM_RATE
     */
    public void setClientComRate(BigDecimal value) {
        setAttributeInternal(CLIENTCOMRATE, value);
    }

    /**
     * Gets the attribute value for COMMISSION using the alias name Commission.
     * @return the COMMISSION
     */
    public BigDecimal getCommission() {
        return (BigDecimal) getAttributeInternal(COMMISSION);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISSION using the alias name Commission.
     * @param value value to set the COMMISSION
     */
    public void setCommission(BigDecimal value) {
        setAttributeInternal(COMMISSION, value);
    }

    /**
     * Gets the attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @return the COMPULSORY_SPOT
     */
    public String getCompulsorySpot() {
        return (String) getAttributeInternal(COMPULSORYSPOT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPULSORY_SPOT using the alias name CompulsorySpot.
     * @param value value to set the COMPULSORY_SPOT
     */
    public void setCompulsorySpot(String value) {
        setAttributeInternal(COMPULSORYSPOT, value);
    }

    /**
     * Gets the attribute value for CONTRACT_NO using the alias name ContractNo.
     * @return the CONTRACT_NO
     */
    public String getContractNo() {
        return (String) getAttributeInternal(CONTRACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_NO using the alias name ContractNo.
     * @param value value to set the CONTRACT_NO
     */
    public void setContractNo(String value) {
        setAttributeInternal(CONTRACTNO, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DT using the alias name CreationDt.
     * @return the CREATION_DT
     */
    public Timestamp getCreationDt() {
        return (Timestamp) getAttributeInternal(CREATIONDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DT using the alias name CreationDt.
     * @param value value to set the CREATION_DT
     */
    public void setCreationDt(Timestamp value) {
        setAttributeInternal(CREATIONDT, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @return the EXCHANGE_ID
     */
    public Integer getExchangeId() {
        return (Integer) getAttributeInternal(EXCHANGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_ID using the alias name ExchangeId.
     * @param value value to set the EXCHANGE_ID
     */
    public void setExchangeId(Integer value) {
        setAttributeInternal(EXCHANGEID, value);
    }

    /**
     * Gets the attribute value for HOWLA_CHARGE using the alias name HowlaCharge.
     * @return the HOWLA_CHARGE
     */
    public BigDecimal getHowlaCharge() {
        return (BigDecimal) getAttributeInternal(HOWLACHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOWLA_CHARGE using the alias name HowlaCharge.
     * @param value value to set the HOWLA_CHARGE
     */
    public void setHowlaCharge(BigDecimal value) {
        setAttributeInternal(HOWLACHARGE, value);
    }

    /**
     * Gets the attribute value for HOWLA_TYPE using the alias name HowlaType.
     * @return the HOWLA_TYPE
     */
    public String getHowlaType() {
        return (String) getAttributeInternal(HOWLATYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOWLA_TYPE using the alias name HowlaType.
     * @param value value to set the HOWLA_TYPE
     */
    public void setHowlaType(String value) {
        setAttributeInternal(HOWLATYPE, value);
    }

    /**
     * Gets the attribute value for IMPORT_FILE_ID using the alias name ImportFileId.
     * @return the IMPORT_FILE_ID
     */
    public Integer getImportFileId() {
        return (Integer) getAttributeInternal(IMPORTFILEID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_FILE_ID using the alias name ImportFileId.
     * @param value value to set the IMPORT_FILE_ID
     */
    public void setImportFileId(Integer value) {
        setAttributeInternal(IMPORTFILEID, value);
    }

    /**
     * Gets the attribute value for INSTRUMENT_CODE using the alias name InstrumentCode.
     * @return the INSTRUMENT_CODE
     */
    public String getInstrumentCode() {
        return (String) getAttributeInternal(INSTRUMENTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTRUMENT_CODE using the alias name InstrumentCode.
     * @param value value to set the INSTRUMENT_CODE
     */
    public void setInstrumentCode(String value) {
        setAttributeInternal(INSTRUMENTCODE, value);
    }

    /**
     * Gets the attribute value for INSTRUMENT_GROUP using the alias name InstrumentGroup.
     * @return the INSTRUMENT_GROUP
     */
    public String getInstrumentGroup() {
        return (String) getAttributeInternal(INSTRUMENTGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTRUMENT_GROUP using the alias name InstrumentGroup.
     * @param value value to set the INSTRUMENT_GROUP
     */
    public void setInstrumentGroup(String value) {
        setAttributeInternal(INSTRUMENTGROUP, value);
    }

    /**
     * Gets the attribute value for INSTRUMENT_ID using the alias name InstrumentId.
     * @return the INSTRUMENT_ID
     */
    public Integer getInstrumentId() {
        return (Integer) getAttributeInternal(INSTRUMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTRUMENT_ID using the alias name InstrumentId.
     * @param value value to set the INSTRUMENT_ID
     */
    public void setInstrumentId(Integer value) {
        setAttributeInternal(INSTRUMENTID, value);
    }

    /**
     * Gets the attribute value for INVESTOR_CODE using the alias name InvestorCode.
     * @return the INVESTOR_CODE
     */
    public String getInvestorCode() {
        return (String) getAttributeInternal(INVESTORCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVESTOR_CODE using the alias name InvestorCode.
     * @param value value to set the INVESTOR_CODE
     */
    public void setInvestorCode(String value) {
        setAttributeInternal(INVESTORCODE, value);
    }

    /**
     * Gets the attribute value for IS_BDA using the alias name IsBda.
     * @return the IS_BDA
     */
    public String getIsBda() {
        return (String) getAttributeInternal(ISBDA);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_BDA using the alias name IsBda.
     * @param value value to set the IS_BDA
     */
    public void setIsBda(String value) {
        setAttributeInternal(ISBDA, value);
    }

    /**
     * Gets the attribute value for IS_FOREIGN using the alias name IsForeign.
     * @return the IS_FOREIGN
     */
    public String getIsForeign() {
        return (String) getAttributeInternal(ISFOREIGN);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_FOREIGN using the alias name IsForeign.
     * @param value value to set the IS_FOREIGN
     */
    public void setIsForeign(String value) {
        setAttributeInternal(ISFOREIGN, value);
    }

    /**
     * Gets the attribute value for LAGA_CHARGE using the alias name LagaCharge.
     * @return the LAGA_CHARGE
     */
    public BigDecimal getLagaCharge() {
        return (BigDecimal) getAttributeInternal(LAGACHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAGA_CHARGE using the alias name LagaCharge.
     * @param value value to set the LAGA_CHARGE
     */
    public void setLagaCharge(BigDecimal value) {
        setAttributeInternal(LAGACHARGE, value);
    }

    /**
     * Gets the attribute value for MARKET_TYPE using the alias name MarketType.
     * @return the MARKET_TYPE
     */
    public String getMarketType() {
        return (String) getAttributeInternal(MARKETTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MARKET_TYPE using the alias name MarketType.
     * @param value value to set the MARKET_TYPE
     */
    public void setMarketType(String value) {
        setAttributeInternal(MARKETTYPE, value);
    }

    /**
     * Gets the attribute value for MBANK_ID using the alias name MbankId.
     * @return the MBANK_ID
     */
    public Integer getMbankId() {
        return (Integer) getAttributeInternal(MBANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for MBANK_ID using the alias name MbankId.
     * @param value value to set the MBANK_ID
     */
    public void setMbankId(Integer value) {
        setAttributeInternal(MBANKID, value);
    }

    /**
     * Gets the attribute value for NEW_COMM_RATE using the alias name NewCommRate.
     * @return the NEW_COMM_RATE
     */
    public BigDecimal getNewCommRate() {
        return (BigDecimal) getAttributeInternal(NEWCOMMRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_COMM_RATE using the alias name NewCommRate.
     * @param value value to set the NEW_COMM_RATE
     */
    public void setNewCommRate(BigDecimal value) {
        setAttributeInternal(NEWCOMMRATE, value);
    }

    /**
     * Gets the attribute value for ORG_BRANCH_ID using the alias name OrgBranchId.
     * @return the ORG_BRANCH_ID
     */
    public Integer getOrgBranchId() {
        return (Integer) getAttributeInternal(ORGBRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_BRANCH_ID using the alias name OrgBranchId.
     * @param value value to set the ORG_BRANCH_ID
     */
    public void setOrgBranchId(Integer value) {
        setAttributeInternal(ORGBRANCHID, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public BigDecimal getPrice() {
        return (BigDecimal) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(BigDecimal value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ID using the alias name ProductId.
     * @return the PRODUCT_ID
     */
    public Integer getProductId() {
        return (Integer) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ID using the alias name ProductId.
     * @param value value to set the PRODUCT_ID
     */
    public void setProductId(Integer value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Long getQuantity() {
        return (Long) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Long value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TRACER_NO using the alias name TracerNo.
     * @return the TRACER_NO
     */
    public Integer getTracerNo() {
        return (Integer) getAttributeInternal(TRACERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TRACER_NO using the alias name TracerNo.
     * @param value value to set the TRACER_NO
     */
    public void setTracerNo(Integer value) {
        setAttributeInternal(TRACERNO, value);
    }

    /**
     * Gets the attribute value for TRADE_ID using the alias name TradeId.
     * @return the TRADE_ID
     */
    public Integer getTradeId() {
        return (Integer) getAttributeInternal(TRADEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_ID using the alias name TradeId.
     * @param value value to set the TRADE_ID
     */
    public void setTradeId(Integer value) {
        setAttributeInternal(TRADEID, value);
    }

    /**
     * Gets the attribute value for TRADE_TIME using the alias name TradeTime.
     * @return the TRADE_TIME
     */
    public String getTradeTime() {
        return (String) getAttributeInternal(TRADETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE_TIME using the alias name TradeTime.
     * @param value value to set the TRADE_TIME
     */
    public void setTradeTime(String value) {
        setAttributeInternal(TRADETIME, value);
    }

    /**
     * Gets the attribute value for TRADER_ID using the alias name TraderId.
     * @return the TRADER_ID
     */
    public String getTraderId() {
        return (String) getAttributeInternal(TRADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADER_ID using the alias name TraderId.
     * @param value value to set the TRADER_ID
     */
    public void setTraderId(String value) {
        setAttributeInternal(TRADERID, value);
    }

    /**
     * Gets the attribute value for TRADING_DATE using the alias name TradingDate.
     * @return the TRADING_DATE
     */
    public Timestamp getTradingDate() {
        return (Timestamp) getAttributeInternal(TRADINGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADING_DATE using the alias name TradingDate.
     * @param value value to set the TRADING_DATE
     */
    public void setTradingDate(Timestamp value) {
        setAttributeInternal(TRADINGDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
