package leads.capita.trade.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 16:18:16 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TradesVOImpl() {
    }

    /**
     * Returns the bind variable value for branch_id.
     * @return bind variable value for branch_id
     */
    public Integer getbranch_id() {
        return (Integer)getNamedWhereClauseParam("branch_id");
    }

    /**
     * Sets <code>value</code> for bind variable branch_id.
     * @param value value to bind as branch_id
     */
    public void setbranch_id(Integer value) {
        setNamedWhereClauseParam("branch_id", value);
    }
}
