package leads.capita.trade.model.view.client;

import leads.capita.trade.model.view.common.TradePriceFileVO;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 13:47:22 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradePriceFileVOClient extends ViewUsageImpl implements TradePriceFileVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TradePriceFileVOClient() {
    }


    public long count() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"count",null,null);
        return ((Long)_ret).longValue();
    }

    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getQueryHitCount",new String [] {"oracle.jbo.server.ViewRowSetImpl"},new Object[] {viewRowSet});
        return ((Long)_ret).longValue();
    }
}
