package leads.capita.trade.model.view.client;

import java.math.BigDecimal;

import leads.capita.trade.model.view.common.TradePriceFileVORow;

import oracle.jbo.RowSet;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 20:38:30 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradePriceFileVORowClient extends RowImpl implements TradePriceFileVORow {
    /**
     * This is the default constructor (do not remove).
     */
    public TradePriceFileVORowClient() {
    }


    public int count() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"count",null,null);
        return ((Integer)_ret).intValue();
    }

    public oracle.jbo.Row getImportExtFilesVO() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getImportExtFilesVO",null,null);
        return (oracle.jbo.Row)_ret;
    }

    public RowSet getInstrumentGroupLOV() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getInstrumentGroupLOV",null,null);
        return (RowSet)_ret;
    }

    public void setImportExtFilesVO(oracle.jbo.Row value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setImportExtFilesVO",new String [] {"oracle.jbo.Row"},new Object[] {value});
        return;
    }

    public BigDecimal getClosePrice() {
        return (BigDecimal)getAttribute("ClosePrice");
    }

    public Integer getExchangeId() {
        return (Integer)getAttribute("ExchangeId");
    }

    public BigDecimal getHighPrice() {
        return (BigDecimal)getAttribute("HighPrice");
    }

    public Integer getImportId() {
        return (Integer)getAttribute("ImportId");
    }

    public String getInstrCode() {
        return (String)getAttribute("InstrCode");
    }

    public String getInstrGroup() {
        return (String)getAttribute("InstrGroup");
    }

    public String getInstrIsin() {
        return (String)getAttribute("InstrIsin");
    }

    public BigDecimal getLowPrice() {
        return (BigDecimal)getAttribute("LowPrice");
    }

    public String getMarketType() {
        return (String)getAttribute("MarketType");
    }

    public BigDecimal getOpenPrice() {
        return (BigDecimal)getAttribute("OpenPrice");
    }

    public Timestamp getPriceDate() {
        return (Timestamp)getAttribute("PriceDate");
    }

    public Timestamp getProcDate() {
        return (Timestamp)getAttribute("ProcDate");
    }

    public String getProcStatus() {
        return (String)getAttribute("ProcStatus");
    }

    public RowID getRowID() {
        return (RowID)getAttribute("RowID");
    }

    public Integer getSeqNo() {
        return (Integer)getAttribute("SeqNo");
    }

    public Integer getTracerNo() {
        return (Integer)getAttribute("java.lang.Long");
    }

    public String getTradeTime() {
        return (String)getAttribute("TradeTime");
    }

    public String getValidStatus() {
        return (String)getAttribute("ValidStatus");
    }

    public void setClosePrice(BigDecimal value) {
        setAttribute("ClosePrice", value);
    }

    public void setExchangeId(Integer value) {
        setAttribute("ExchangeId", value);
    }

    public void setHighPrice(BigDecimal value) {
        setAttribute("HighPrice", value);
    }

    public void setImportId(Integer value) {
        setAttribute("ImportId", value);
    }

    public void setInstrCode(String value) {
        setAttribute("InstrCode", value);
    }

    public void setInstrGroup(String value) {
        setAttribute("InstrGroup", value);
    }

    public void setInstrIsin(String value) {
        setAttribute("InstrIsin", value);
    }

    public void setLowPrice(BigDecimal value) {
        setAttribute("LowPrice", value);
    }

    public void setMarketType(String value) {
        setAttribute("MarketType", value);
    }

    public void setOpenPrice(BigDecimal value) {
        setAttribute("OpenPrice", value);
    }

    public void setPriceDate(Timestamp value) {
        setAttribute("PriceDate", value);
    }

    public void setProcDate(Timestamp value) {
        setAttribute("ProcDate", value);
    }

    public void setProcStatus(String value) {
        setAttribute("ProcStatus", value);
    }

    public void setRowID(RowID value) {
        setAttribute("RowID", value);
    }

    public void setSeqNo(Integer value) {
        setAttribute("SeqNo", value);
    }

    public void setTracerNo(Integer value) {
        setAttribute("java.lang.Long", value);
    }

    public void setTradeTime(String value) {
        setAttribute("TradeTime", value);
    }

    public void setValidStatus(String value) {
        setAttribute("ValidStatus", value);
    }
}
