package leads.capita.trade.model.entity;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 13 12:07:34 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradesImpl extends EntityImpl {
    /**
     * Add locking logic here.
     */
    public void lock() {
       // super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        //super.doDML(operation, e);
        ///
        System.out.println("Before Operation");
        if(operation == this.DML_UPDATE){
                    System.out.println("after Operation");
                    Double newCommision =Double.valueOf(this.getCommission().toString()) ;
                    Double oldCommision = Double.valueOf(this.getPostedAttribute(COMMISSION).toString()) ;
                    if(newCommision != null && oldCommision != null && newCommision.compareTo(oldCommision) != 0){
                        System.out.println("In IF--"+this.getAccountId());
                       // Integer importId = this.getImportFileId();
                        ViewObjectImpl tradeChangesView = (ViewObjectImpl)this.getDBTransaction().getRootApplicationModule().findViewObject("TradeChangesView");
                        Row tradeChangesRow = tradeChangesView.createRow();
                        tradeChangesRow.setAttribute("AccountId",this.getAccountId() );
                        tradeChangesRow.setAttribute("BrokerId",this.getBrokerId() );
                        tradeChangesRow.setAttribute("BuySell", this.getBuySell());
                        tradeChangesRow.setAttribute("ClientComRate",this.getClientComRate() );
                        tradeChangesRow.setAttribute("Commission", newCommision);
                        tradeChangesRow.setAttribute("ExchangeId", this.getExchangeId());
                        tradeChangesRow.setAttribute("ImportFileId", this.getImportFileId());
                        tradeChangesRow.setAttribute("InstrumentId", this.getInstrumentId());
                        tradeChangesRow.setAttribute("MarketType", this.getMarketType());
                        tradeChangesRow.setAttribute("Price",this.getPrice());
                        tradeChangesRow.setAttribute("Quantity", this.getQuantity());
                        tradeChangesRow.setAttribute("TradingDate", this.getTradingDate());
                        

                        System.out.println("Before insert Row");
                        tradeChangesView.insertRow(tradeChangesRow);
                        System.out.println("After insert Row");
                    }
                }

        ///
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TradeId {
            public Object get(TradesImpl obj) {
                return obj.getTradeId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setTradeId((Integer)value);
            }
        }
        ,
        OrgBranchId {
            public Object get(TradesImpl obj) {
                return obj.getOrgBranchId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setOrgBranchId((Integer)value);
            }
        }
        ,
        BrokerId {
            public Object get(TradesImpl obj) {
                return obj.getBrokerId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setBrokerId((Integer)value);
            }
        }
        ,
        TradingDate {
            public Object get(TradesImpl obj) {
                return obj.getTradingDate();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setTradingDate((Timestamp)value);
            }
        }
        ,
        ExchangeId {
            public Object get(TradesImpl obj) {
                return obj.getExchangeId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setExchangeId((Integer)value);
            }
        }
        ,
        InvestorCode {
            public Object get(TradesImpl obj) {
                return obj.getInvestorCode();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setInvestorCode((String)value);
            }
        }
        ,
        AccountId {
            public Object get(TradesImpl obj) {
                return obj.getAccountId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setAccountId((Long)value);
            }
        }
        ,
        InstrumentCode {
            public Object get(TradesImpl obj) {
                return obj.getInstrumentCode();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setInstrumentCode((String)value);
            }
        }
        ,
        InstrumentId {
            public Object get(TradesImpl obj) {
                return obj.getInstrumentId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setInstrumentId((Integer)value);
            }
        }
        ,
        InstrumentGroup {
            public Object get(TradesImpl obj) {
                return obj.getInstrumentGroup();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setInstrumentGroup((String)value);
            }
        }
        ,
        BuySell {
            public Object get(TradesImpl obj) {
                return obj.getBuySell();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setBuySell((String)value);
            }
        }
        ,
        Quantity {
            public Object get(TradesImpl obj) {
                return obj.getQuantity();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setQuantity((Long)value);
            }
        }
        ,
        Price {
            public Object get(TradesImpl obj) {
                return obj.getPrice();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setPrice((BigDecimal)value);
            }
        }
        ,
        TraderId {
            public Object get(TradesImpl obj) {
                return obj.getTraderId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setTraderId((String)value);
            }
        }
        ,
        MarketType {
            public Object get(TradesImpl obj) {
                return obj.getMarketType();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setMarketType((String)value);
            }
        }
        ,
        CompulsorySpot {
            public Object get(TradesImpl obj) {
                return obj.getCompulsorySpot();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setCompulsorySpot((String)value);
            }
        }
        ,
        HowlaType {
            public Object get(TradesImpl obj) {
                return obj.getHowlaType();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setHowlaType((String)value);
            }
        }
        ,
        IsForeign {
            public Object get(TradesImpl obj) {
                return obj.getIsForeign();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setIsForeign((String)value);
            }
        }
        ,
        HowlaCharge {
            public Object get(TradesImpl obj) {
                return obj.getHowlaCharge();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setHowlaCharge((BigDecimal)value);
            }
        }
        ,
        LagaCharge {
            public Object get(TradesImpl obj) {
                return obj.getLagaCharge();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setLagaCharge((BigDecimal)value);
            }
        }
        ,
        AitCharge {
            public Object get(TradesImpl obj) {
                return obj.getAitCharge();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setAitCharge((BigDecimal)value);
            }
        }
        ,
        ContractNo {
            public Object get(TradesImpl obj) {
                return obj.getContractNo();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setContractNo((String)value);
            }
        }
        ,
        TradeTime {
            public Object get(TradesImpl obj) {
                return obj.getTradeTime();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setTradeTime((String)value);
            }
        }
        ,
        Status {
            public Object get(TradesImpl obj) {
                return obj.getStatus();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        ImportFileId {
            public Object get(TradesImpl obj) {
                return obj.getImportFileId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setImportFileId((Integer)value);
            }
        }
        ,
        TracerNo {
            public Object get(TradesImpl obj) {
                return obj.getTracerNo();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setTracerNo((Integer)value);
            }
        }
        ,
        CreatedBy {
            public Object get(TradesImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDt {
            public Object get(TradesImpl obj) {
                return obj.getCreationDt();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setCreationDt((Timestamp)value);
            }
        }
        ,
        MbankId {
            public Object get(TradesImpl obj) {
                return obj.getMbankId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setMbankId((Integer)value);
            }
        }
        ,
        Commission {
            public Object get(TradesImpl obj) {
                return obj.getCommission();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setCommission((BigDecimal)value);
            }
        }
        ,
        IsBda {
            public Object get(TradesImpl obj) {
                return obj.getIsBda();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setIsBda((String)value);
            }
        }
        ,
        ProductId {
            public Object get(TradesImpl obj) {
                return obj.getProductId();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setProductId((Integer)value);
            }
        }
        ,
        ClientComRate {
            public Object get(TradesImpl obj) {
                return obj.getClientComRate();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setClientComRate((BigDecimal)value);
            }
        }
        ,
        BrokerComRate {
            public Object get(TradesImpl obj) {
                return obj.getBrokerComRate();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setBrokerComRate((BigDecimal)value);
            }
        }
        ,
        NewCommRate {
            public Object get(TradesImpl obj) {
                return obj.getNewCommRate();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setNewCommRate((BigDecimal)value);
            }
        }
        ,
        Exchanges {
            public Object get(TradesImpl obj) {
                return obj.getExchanges();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setExchanges((EntityImpl)value);
            }
        }
        ,
        Products {
            public Object get(TradesImpl obj) {
                return obj.getProducts();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setProducts((EntityImpl)value);
            }
        }
        ,
        InvestorAccounts {
            public Object get(TradesImpl obj) {
                return obj.getInvestorAccounts();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setInvestorAccounts((EntityImpl)value);
            }
        }
        ,
        ImportExtFiles {
            public Object get(TradesImpl obj) {
                return obj.getImportExtFiles();
            }

            public void put(TradesImpl obj, Object value) {
                obj.setImportExtFiles((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TradesImpl object);

        public abstract void put(TradesImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int TRADEID = AttributesEnum.TradeId.index();
    public static final int ORGBRANCHID = AttributesEnum.OrgBranchId.index();
    public static final int BROKERID = AttributesEnum.BrokerId.index();
    public static final int TRADINGDATE = AttributesEnum.TradingDate.index();
    public static final int EXCHANGEID = AttributesEnum.ExchangeId.index();
    public static final int INVESTORCODE = AttributesEnum.InvestorCode.index();
    public static final int ACCOUNTID = AttributesEnum.AccountId.index();
    public static final int INSTRUMENTCODE = AttributesEnum.InstrumentCode.index();
    public static final int INSTRUMENTID = AttributesEnum.InstrumentId.index();
    public static final int INSTRUMENTGROUP = AttributesEnum.InstrumentGroup.index();
    public static final int BUYSELL = AttributesEnum.BuySell.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int TRADERID = AttributesEnum.TraderId.index();
    public static final int MARKETTYPE = AttributesEnum.MarketType.index();
    public static final int COMPULSORYSPOT = AttributesEnum.CompulsorySpot.index();
    public static final int HOWLATYPE = AttributesEnum.HowlaType.index();
    public static final int ISFOREIGN = AttributesEnum.IsForeign.index();
    public static final int HOWLACHARGE = AttributesEnum.HowlaCharge.index();
    public static final int LAGACHARGE = AttributesEnum.LagaCharge.index();
    public static final int AITCHARGE = AttributesEnum.AitCharge.index();
    public static final int CONTRACTNO = AttributesEnum.ContractNo.index();
    public static final int TRADETIME = AttributesEnum.TradeTime.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int IMPORTFILEID = AttributesEnum.ImportFileId.index();
    public static final int TRACERNO = AttributesEnum.TracerNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDT = AttributesEnum.CreationDt.index();
    public static final int MBANKID = AttributesEnum.MbankId.index();
    public static final int COMMISSION = AttributesEnum.Commission.index();
    public static final int ISBDA = AttributesEnum.IsBda.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int CLIENTCOMRATE = AttributesEnum.ClientComRate.index();
    public static final int BROKERCOMRATE = AttributesEnum.BrokerComRate.index();
    public static final int NEWCOMMRATE = AttributesEnum.NewCommRate.index();
    public static final int EXCHANGES = AttributesEnum.Exchanges.index();
    public static final int PRODUCTS = AttributesEnum.Products.index();
    public static final int INVESTORACCOUNTS = AttributesEnum.InvestorAccounts.index();
    public static final int IMPORTEXTFILES = AttributesEnum.ImportExtFiles.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TradesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("leads.capita.trade.model.entity.Trades");
    }

    /**
     * Gets the attribute value for TradeId, using the alias name TradeId.
     * @return the value of TradeId
     */
    public Integer getTradeId() {
        return (Integer)getAttributeInternal(TRADEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeId.
     * @param value value to set the TradeId
     */
    public void setTradeId(Integer value) {
        setAttributeInternal(TRADEID, value);
    }

    /**
     * Gets the attribute value for OrgBranchId, using the alias name OrgBranchId.
     * @return the value of OrgBranchId
     */
    public Integer getOrgBranchId() {
        return (Integer)getAttributeInternal(ORGBRANCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgBranchId.
     * @param value value to set the OrgBranchId
     */
    public void setOrgBranchId(Integer value) {
        setAttributeInternal(ORGBRANCHID, value);
    }

    /**
     * Gets the attribute value for BrokerId, using the alias name BrokerId.
     * @return the value of BrokerId
     */
    public Integer getBrokerId() {
        return (Integer)getAttributeInternal(BROKERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerId.
     * @param value value to set the BrokerId
     */
    public void setBrokerId(Integer value) {
        setAttributeInternal(BROKERID, value);
    }

    /**
     * Gets the attribute value for TradingDate, using the alias name TradingDate.
     * @return the value of TradingDate
     */
    public Timestamp getTradingDate() {
        return (Timestamp)getAttributeInternal(TRADINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradingDate.
     * @param value value to set the TradingDate
     */
    public void setTradingDate(Timestamp value) {
        setAttributeInternal(TRADINGDATE, value);
    }

    /**
     * Gets the attribute value for ExchangeId, using the alias name ExchangeId.
     * @return the value of ExchangeId
     */
    public Integer getExchangeId() {
        return (Integer)getAttributeInternal(EXCHANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeId.
     * @param value value to set the ExchangeId
     */
    public void setExchangeId(Integer value) {
        setAttributeInternal(EXCHANGEID, value);
    }

    /**
     * Gets the attribute value for InvestorCode, using the alias name InvestorCode.
     * @return the value of InvestorCode
     */
    public String getInvestorCode() {
        return (String)getAttributeInternal(INVESTORCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvestorCode.
     * @param value value to set the InvestorCode
     */
    public void setInvestorCode(String value) {
        setAttributeInternal(INVESTORCODE, value);
    }

    /**
     * Gets the attribute value for AccountId, using the alias name AccountId.
     * @return the value of AccountId
     */
    public Long getAccountId() {
        return (Long)getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccountId.
     * @param value value to set the AccountId
     */
    public void setAccountId(Long value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for InstrumentCode, using the alias name InstrumentCode.
     * @return the value of InstrumentCode
     */
    public String getInstrumentCode() {
        return (String)getAttributeInternal(INSTRUMENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstrumentCode.
     * @param value value to set the InstrumentCode
     */
    public void setInstrumentCode(String value) {
        setAttributeInternal(INSTRUMENTCODE, value);
    }

    /**
     * Gets the attribute value for InstrumentId, using the alias name InstrumentId.
     * @return the value of InstrumentId
     */
    public Integer getInstrumentId() {
        return (Integer)getAttributeInternal(INSTRUMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstrumentId.
     * @param value value to set the InstrumentId
     */
    public void setInstrumentId(Integer value) {
        setAttributeInternal(INSTRUMENTID, value);
    }

    /**
     * Gets the attribute value for InstrumentGroup, using the alias name InstrumentGroup.
     * @return the value of InstrumentGroup
     */
    public String getInstrumentGroup() {
        return (String)getAttributeInternal(INSTRUMENTGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstrumentGroup.
     * @param value value to set the InstrumentGroup
     */
    public void setInstrumentGroup(String value) {
        setAttributeInternal(INSTRUMENTGROUP, value);
    }

    /**
     * Gets the attribute value for BuySell, using the alias name BuySell.
     * @return the value of BuySell
     */
    public String getBuySell() {
        return (String)getAttributeInternal(BUYSELL);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuySell.
     * @param value value to set the BuySell
     */
    public void setBuySell(String value) {
        setAttributeInternal(BUYSELL, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public Long getQuantity() {
        return (Long)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Long value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for Price, using the alias name Price.
     * @return the value of Price
     */
    public BigDecimal getPrice() {
        return (BigDecimal)getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Price.
     * @param value value to set the Price
     */
    public void setPrice(BigDecimal value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for TraderId, using the alias name TraderId.
     * @return the value of TraderId
     */
    public String getTraderId() {
        return (String)getAttributeInternal(TRADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraderId.
     * @param value value to set the TraderId
     */
    public void setTraderId(String value) {
        setAttributeInternal(TRADERID, value);
    }

    /**
     * Gets the attribute value for MarketType, using the alias name MarketType.
     * @return the value of MarketType
     */
    public String getMarketType() {
        return (String)getAttributeInternal(MARKETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarketType.
     * @param value value to set the MarketType
     */
    public void setMarketType(String value) {
        setAttributeInternal(MARKETTYPE, value);
    }

    /**
     * Gets the attribute value for CompulsorySpot, using the alias name CompulsorySpot.
     * @return the value of CompulsorySpot
     */
    public String getCompulsorySpot() {
        return (String)getAttributeInternal(COMPULSORYSPOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompulsorySpot.
     * @param value value to set the CompulsorySpot
     */
    public void setCompulsorySpot(String value) {
        setAttributeInternal(COMPULSORYSPOT, value);
    }

    /**
     * Gets the attribute value for HowlaType, using the alias name HowlaType.
     * @return the value of HowlaType
     */
    public String getHowlaType() {
        return (String)getAttributeInternal(HOWLATYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HowlaType.
     * @param value value to set the HowlaType
     */
    public void setHowlaType(String value) {
        setAttributeInternal(HOWLATYPE, value);
    }

    /**
     * Gets the attribute value for IsForeign, using the alias name IsForeign.
     * @return the value of IsForeign
     */
    public String getIsForeign() {
        return (String)getAttributeInternal(ISFOREIGN);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsForeign.
     * @param value value to set the IsForeign
     */
    public void setIsForeign(String value) {
        setAttributeInternal(ISFOREIGN, value);
    }

    /**
     * Gets the attribute value for HowlaCharge, using the alias name HowlaCharge.
     * @return the value of HowlaCharge
     */
    public BigDecimal getHowlaCharge() {
        return (BigDecimal)getAttributeInternal(HOWLACHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HowlaCharge.
     * @param value value to set the HowlaCharge
     */
    public void setHowlaCharge(BigDecimal value) {
        setAttributeInternal(HOWLACHARGE, value);
    }

    /**
     * Gets the attribute value for LagaCharge, using the alias name LagaCharge.
     * @return the value of LagaCharge
     */
    public BigDecimal getLagaCharge() {
        return (BigDecimal)getAttributeInternal(LAGACHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LagaCharge.
     * @param value value to set the LagaCharge
     */
    public void setLagaCharge(BigDecimal value) {
        setAttributeInternal(LAGACHARGE, value);
    }

    /**
     * Gets the attribute value for AitCharge, using the alias name AitCharge.
     * @return the value of AitCharge
     */
    public BigDecimal getAitCharge() {
        return (BigDecimal)getAttributeInternal(AITCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AitCharge.
     * @param value value to set the AitCharge
     */
    public void setAitCharge(BigDecimal value) {
        setAttributeInternal(AITCHARGE, value);
    }

    /**
     * Gets the attribute value for ContractNo, using the alias name ContractNo.
     * @return the value of ContractNo
     */
    public String getContractNo() {
        return (String)getAttributeInternal(CONTRACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractNo.
     * @param value value to set the ContractNo
     */
    public void setContractNo(String value) {
        setAttributeInternal(CONTRACTNO, value);
    }

    /**
     * Gets the attribute value for TradeTime, using the alias name TradeTime.
     * @return the value of TradeTime
     */
    public String getTradeTime() {
        return (String)getAttributeInternal(TRADETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeTime.
     * @param value value to set the TradeTime
     */
    public void setTradeTime(String value) {
        setAttributeInternal(TRADETIME, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ImportFileId, using the alias name ImportFileId.
     * @return the value of ImportFileId
     */
    public Integer getImportFileId() {
        return (Integer)getAttributeInternal(IMPORTFILEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImportFileId.
     * @param value value to set the ImportFileId
     */
    public void setImportFileId(Integer value) {
        setAttributeInternal(IMPORTFILEID, value);
    }

    /**
     * Gets the attribute value for TracerNo, using the alias name TracerNo.
     * @return the value of TracerNo
     */
    public Integer getTracerNo() {
        return (Integer)getAttributeInternal(TRACERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TracerNo.
     * @param value value to set the TracerNo
     */
    public void setTracerNo(Integer value) {
        setAttributeInternal(TRACERNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDt, using the alias name CreationDt.
     * @return the value of CreationDt
     */
    public Timestamp getCreationDt() {
        return (Timestamp)getAttributeInternal(CREATIONDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDt.
     * @param value value to set the CreationDt
     */
    public void setCreationDt(Timestamp value) {
        setAttributeInternal(CREATIONDT, value);
    }

    /**
     * Gets the attribute value for MbankId, using the alias name MbankId.
     * @return the value of MbankId
     */
    public Integer getMbankId() {
        return (Integer)getAttributeInternal(MBANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MbankId.
     * @param value value to set the MbankId
     */
    public void setMbankId(Integer value) {
        setAttributeInternal(MBANKID, value);
    }

    /**
     * Gets the attribute value for Commission, using the alias name Commission.
     * @return the value of Commission
     */
    public BigDecimal getCommission() {
        return (BigDecimal)getAttributeInternal(COMMISSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Commission.
     * @param value value to set the Commission
     */
    public void setCommission(BigDecimal value) {
        setAttributeInternal(COMMISSION, value);
    }

    /**
     * Gets the attribute value for IsBda, using the alias name IsBda.
     * @return the value of IsBda
     */
    public String getIsBda() {
        return (String)getAttributeInternal(ISBDA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsBda.
     * @param value value to set the IsBda
     */
    public void setIsBda(String value) {
        setAttributeInternal(ISBDA, value);
    }

    /**
     * Gets the attribute value for ProductId, using the alias name ProductId.
     * @return the value of ProductId
     */
    public Integer getProductId() {
        return (Integer)getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductId.
     * @param value value to set the ProductId
     */
    public void setProductId(Integer value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for ClientComRate, using the alias name ClientComRate.
     * @return the value of ClientComRate
     */
    public BigDecimal getClientComRate() {
        return (BigDecimal)getAttributeInternal(CLIENTCOMRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClientComRate.
     * @param value value to set the ClientComRate
     */
    public void setClientComRate(BigDecimal value) {
        setAttributeInternal(CLIENTCOMRATE, value);
    }

    /**
     * Gets the attribute value for BrokerComRate, using the alias name BrokerComRate.
     * @return the value of BrokerComRate
     */
    public BigDecimal getBrokerComRate() {
        return (BigDecimal)getAttributeInternal(BROKERCOMRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerComRate.
     * @param value value to set the BrokerComRate
     */
    public void setBrokerComRate(BigDecimal value) {
        setAttributeInternal(BROKERCOMRATE, value);
    }

    /**
     * Gets the attribute value for NewCommRate, using the alias name NewCommRate.
     * @return the value of NewCommRate
     */
    public BigDecimal getNewCommRate() {
        return (BigDecimal)getAttributeInternal(NEWCOMMRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewCommRate.
     * @param value value to set the NewCommRate
     */
    public void setNewCommRate(BigDecimal value) {
        setAttributeInternal(NEWCOMMRATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getExchanges() {
        return (EntityImpl)getAttributeInternal(EXCHANGES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setExchanges(EntityImpl value) {
        setAttributeInternal(EXCHANGES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getProducts() {
        return (EntityImpl)getAttributeInternal(PRODUCTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setProducts(EntityImpl value) {
        setAttributeInternal(PRODUCTS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInvestorAccounts() {
        return (EntityImpl)getAttributeInternal(INVESTORACCOUNTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInvestorAccounts(EntityImpl value) {
        setAttributeInternal(INVESTORACCOUNTS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getImportExtFiles() {
        return (EntityImpl)getAttributeInternal(IMPORTEXTFILES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setImportExtFiles(EntityImpl value) {
        setAttributeInternal(IMPORTEXTFILES, value);
    }

    /**
     * @param tradeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer tradeId) {
        return new Key(new Object[]{tradeId});
    }


}
