package leads.capita.trade.model.am;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 11 12:16:56 ALMT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BdaServiceImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BdaServiceImpl() {
    }


    /**
     * Container's getter for TransiantVO.
     * @return TransiantVO
     */
    public ViewObjectImpl getTransiantVO() {
        return (ViewObjectImpl)findViewObject("TransiantVO");
    }


    /**
     * Container's getter for BdaOrdersVO.
     * @return BdaOrdersVO
     */
    public ViewObjectImpl getBdaOrdersVO() {
        return (ViewObjectImpl)findViewObject("BdaOrdersVO");
    }

    /**
     * Container's getter for BdaOrderDetailVO.
     * @return BdaOrderDetailVO
     */
    public ViewObjectImpl getBdaOrderDetailVO() {
        return (ViewObjectImpl)findViewObject("BdaOrderDetailVO");
    }

    /**
     * Container's getter for BdaOrderDetailFkBdaOrderLink.
     * @return BdaOrderDetailFkBdaOrderLink
     */
    public ViewLinkImpl getBdaOrderDetailFkBdaOrderLink() {
        return (ViewLinkImpl)findViewLink("BdaOrderDetailFkBdaOrderLink");
    }

    /**
     * Container's getter for BdaOrdersFilterVO.
     * @return BdaOrdersFilterVO
     */
    public ViewObjectImpl getBdaOrdersFilterVO() {
        return (ViewObjectImpl)findViewObject("BdaOrdersFilterVO");
    }

    /**
     * Container's getter for BdaSalesOrderInvListVO.
     * @return BdaSalesOrderInvListVO
     */
    public ViewObjectImpl getBdaSalesOrderInvListVO() {
        return (ViewObjectImpl)findViewObject("BdaSalesOrderInvListVO");
    }

    /**
     * Container's getter for BdaSalesAllocInvList.
     * @return BdaSalesAllocInvList
     */
    public ViewObjectImpl getBdaSalesAllocInvList() {
        return (ViewObjectImpl)findViewObject("BdaSalesAllocInvList");
    }

    /**
     * Container's getter for BdaOrderDetailDefaultVO.
     * @return BdaOrderDetailDefaultVO
     */
    public ViewObjectImpl getBdaOrderDetailDefaultVO() {
        return (ViewObjectImpl)findViewObject("BdaOrderDetailDefaultVO");
    }

    /**
     * Container's getter for InvestorListForBDALOV.
     * @return InvestorListForBDALOV
     */
    public ViewObjectImpl getInvestorListForBDALOV() {
        return (ViewObjectImpl)findViewObject("InvestorListForBDALOV");
    }

    /**
     * Container's getter for BdaBuyAllocInvList.
     * @return BdaBuyAllocInvList
     */
    public ViewObjectImpl getBdaBuyAllocInvList() {
        return (ViewObjectImpl)findViewObject("BdaBuyAllocInvList");
    }

    /**
     * Container's getter for BdaBuyOrderInvList.
     * @return BdaBuyOrderInvList
     */
    public ViewObjectImpl getBdaBuyOrderInvList() {
        return (ViewObjectImpl)findViewObject("BdaBuyOrderInvList");
    }


    /**
     * Container's getter for BdaBuyOrdersVO.
     * @return BdaBuyOrdersVO
     */
    public ViewObjectImpl getBdaBuyOrdersVO() {
        return (ViewObjectImpl)findViewObject("BdaBuyOrdersVO");
    }

    /**
     * Container's getter for BdaBuyOrdersDetailVO.
     * @return BdaBuyOrdersDetailVO
     */
    public ViewObjectImpl getBdaBuyOrdersDetailVO() {
        return (ViewObjectImpl)findViewObject("BdaBuyOrdersDetailVO");
    }

    /**
     * Container's getter for bdaBuyOrderDetFkBuyOrderLink.
     * @return bdaBuyOrderDetFkBuyOrderLink
     */
    public ViewLinkImpl getbdaBuyOrderDetFkBuyOrderLink() {
        return (ViewLinkImpl)findViewLink("bdaBuyOrderDetFkBuyOrderLink");
    }

    /**
     * Container's getter for AllProductsLOV.
     * @return AllProductsLOV
     */
    public ViewObjectImpl getAllProductsLOV() {
        return (ViewObjectImpl)findViewObject("AllProductsLOV");
    }

    /**
     * Container's getter for BDAProductLOV.
     * @return BDAProductLOV
     */
    public ViewObjectImpl getBDAProductLOV() {
        return (ViewObjectImpl)findViewObject("BDAProductLOV");
    }

    /**
     * Container's getter for BdaOrderDetailForSearchVO.
     * @return BdaOrderDetailForSearchVO
     */
    public ViewObjectImpl getBdaOrderDetailForSearchVO() {
        return (ViewObjectImpl)findViewObject("BdaOrderDetailForSearchVO");
    }

}
