package leads.capita.trade.model.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 13:47:21 BDT 2022
// ---------------------------------------------------------------------
public interface TradePriceFileVO extends ViewObject {
    long count();

    long getQueryHitCount(ViewRowSetImpl viewRowSet);
}
