package leads.capita.trade.model.view.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 20:38:30 BDT 2022
// ---------------------------------------------------------------------
public interface TradePriceFileVORow extends Row {

    Row getImportExtFilesVO();

    RowSet getInstrumentGroupLOV();

    void setImportExtFilesVO(Row value);

    BigDecimal getClosePrice();

    Integer getExchangeId();

    BigDecimal getHighPrice();

    Integer getImportId();

    String getInstrCode();

    String getInstrGroup();

    String getInstrIsin();

    BigDecimal getLowPrice();

    BigDecimal getOpenPrice();

    Timestamp getPriceDate();

    Timestamp getProcDate();

    String getProcStatus();

    RowID getRowID();

    Integer getTracerNo();

    String getTradeTime();

    String getValidStatus();

    void setClosePrice(BigDecimal value);

    void setExchangeId(Integer value);

    void setHighPrice(BigDecimal value);

    void setImportId(Integer value);

    void setInstrCode(String value);

    void setInstrGroup(String value);

    void setInstrIsin(String value);

    void setLowPrice(BigDecimal value);

    void setOpenPrice(BigDecimal value);

    void setPriceDate(Timestamp value);

    void setProcDate(Timestamp value);

    void setProcStatus(String value);

    void setRowID(RowID value);

    void setTracerNo(Integer value);

    void setTradeTime(String value);

    void setValidStatus(String value);

    String getMarketType();

    void setMarketType(String value);

    Integer getSeqNo();

    void setSeqNo(Integer value);


    int count();


}
